### ISSUE TITLE
Bug: [v8 regression] initial text rendering much slower than in v7

### ISSUE THREAD

**Issue by joergplewe** [pixijs/pixijs#10317]
### Current Behavior

Creating new v8 `Text` takes a lot more initial rendering time than v7, factor 2-3x.

### Expected Behavior

v8 should be as fast as v7

### Steps to Reproduce

Observe the behavior in v7 and v8 playgrounds creating 5000 individual `Text`:

- V8: https://www.pixiplayground.com/#/edit/JNVIMPkjPrGutAxV5rpkl
- V7: https://www.pixiplayground.com/#/edit/8S-wckEt11L-1SstlHjlP

Be patient, v8 may feel like a browser crash.

### Environment

- **`pixi.js` version**: v8.0.1
- **Browser & Version**: any
- **OS & Version**: Windows11, MacOS14.4
- **Running Example**: 
V8: https://www.pixiplayground.com/#/edit/JNVIMPkjPrGutAxV5rpkl
V7: https://www.pixiplayground.com/#/edit/8S-wckEt11L-1SstlHjlP

**Comment by GoodBoyDigital** [comment]
hey there @joergplewe, thanks for flagging.

this is actually more of a webGPU bottle neck it seems!

[v8: webGL test](https://www.pixiplayground.com/#/edit/LbR3OpNFb0i0Df0EA9k_p)

WebGPU is slower at uploading textures at the moment it seems (`copyExternalImageToTexture`)

![Image](https://github.com/pixijs/pixijs/assets/3112434/86f66f18-d702-4999-9eda-88e9a72ec6eb)

**Comment by joergplewe** [comment]
Sounds like "no way out"?
Do you advise using WebGL then? In general? Is there a clear advantage of WebGPU elsewhere?

**Comment by GoodBoyDigital** [comment]
Yes, WebGL is faster in many case at the moment. 
WebGPU should be faster for scenes that switch up a lot different things (eg filters / masks / batching).

**Comment by joergplewe** [comment]
@GoodBoyDigital,  issue is not solved, v8(webgl) still a lot slower than v7. 7s against 4s on my notebook. Is this reasonable?

**Comment by UlyssesZh** [comment]
My game is running below 10 fps when using webgpu, and my computer's fan is crazy. Using `preference: 'webgl'` makes it steadily 60 fps.

**Comment by privatestefans** [comment]
It seems using BitmapText performs faster in v8.11.0-webgpu, while using `Text` it needs to redraw the text to a canvas and upload it to the GPU as a texture every time the content changes. BitmapText is more efficient here, because it just need to upload the texture atlas only once. Its initial rendering is also faster than `Text` when using WebGPU.

V8: [initial rendering for BitmapText](https://www.pixiplayground.com/#/edit/qR3YrVN0Rx1q2yMvDMKPf)

<details><summary>Technical analysis when we rapidly change the `Text`:</summary>

---

I’ve investigated the source code, and it appears that in v8.9.2-webgpu, when we update the text rapidly, the `Text` rendering behaves differently -- it uses a cached texture that’s already been drawn: 

https://github.com/pixijs/pixijs/blob/2c0f2e5c4fd949192ef1c7a14e7e4b7f3e18129d/src/scene/text/canvas/CanvasTextSystem.ts#L153-L158

This caching mechanism helps maintain a steady 60 FPS. However, a potential issue is memory usage could increase significantly when rendering a large number of unique text strings.

---

But in v8.11.0-webgpu, that cache was removed -- causing the `getTexture` function being called every time the text changes. As a result, the text must be redrawn to a canvas and uploaded to the GPU as a texture using the following code:

https://github.com/pixijs/pixijs/blob/efa7feb51f8fd7feb1762be278481c849bcebdd9/src/scene/text/canvas/CanvasTextSystem.ts#L90-L96

Because of that, performance dropped to 4 FPS on my machine when using `PIXI.Text`. However, running the same test code but with `BitmapText`, the FPS could stay steady at 60 because it's doesn't need to reupload any texture.

https://www.pixiplayground.com/#/edit/YV9aR-TLe2puNVZAqdBiT

If we have so many text that updates and these text have various width/length, I also noticed some memory leak where `cachedGroups` also grows rapidly because `generateTextureBatchBindGroup()` got called so many times:

https://github.com/pixijs/pixijs/blob/efa7feb51f8fd7feb1762be278481c849bcebdd9/src/rendering/batcher/gpu/getTextureBatchBindGroup.ts#L6-L26

Maybe these details can help Pixi maintainer to do some investigation.
</details>
