### ISSUE TITLE
Bug: `loadTextures` ignores provided format

### ISSUE THREAD

**Issue by elsassph** [pixijs/pixijs#10378]
### Current Behavior

Our images are hosted without a recognizable file extension.

`Assets` API seem to indicate that the format can be optionally provided through `UnresolvedAsset`.

Unfortunately, `loadTextures` ignores this information and only looks up the extension from the URL.

### Expected Behavior

`loadTextures` should use the provided format.

### Steps to Reproduce

```
const texture = await Assets.load({
  src: imageUrlWithoutRecognizableExtension,
  format: "png"
});
```

### Environment

- **`pixi.js` version**: 8.0
- **Browser & Version**: latest Chrome
- **OS & Version**: latest MacOS
- **Running Example**: https://pixiplayground.com/#/edit/u3XDHb6c_54y_f22YF1IV

### Possible Solution

One workaround that seems to work is to specify the `loadParser` as:
```
const texture = await Assets.load({
  src: imageUrlWithoutRecognizableExtension,
  loadParser: "loadTextures"
});
```

It would be great to add this information in the documentation BTW, because it's really arcane.

**Comment by bigtimebuddy** [comment]
loadParser is indeed the correct solution to this problem. Welcome PR if someone wants to add more explicit mention in the docs or to the [guides](https://pixijs.com/8.x/guides/components/assets).

**Comment by elsassph** [comment]
What is the role of the `format` option then?

**Comment by bigtimebuddy** [comment]
Good question @elsassph. The `format` is similar to `resolution` in that they are used by the Assets' Resolver figure out which asset to load based on the developer's preferences. For example, maybe on a mobile device you want to prefer resolution of `1` and a format of `webp`. These attributes allow you to explicitly define that instead of inferring from the filename (however resolution/format _can_ be inferred from `src`, e.g., `image@2x.png` would be `2` resolution and `png` format). It's helpful if you are shipping cross-platform assets like compressed textures, or image formats like avif that might not have universal support to be able to define fallbacks.

**Comment by elsassph** [comment]
Thanks, I'll let you guys document that ;)
