### ISSUE TITLE
Bug: Small ellipse is not smooth, When a large scale transform is applied to the container

### ISSUE THREAD

**Issue by F-star** [pixijs/pixijs#10495]
### Current Behavior

Small ellipse is not smooth, When a large scale transform is applied to the container, but also rounded rectangle.

![smooth](https://github.com/pixijs/pixijs/assets/18698939/462b71f3-0ef7-4f4d-97fb-022d05faabad)

### Expected Behavior

be smooth

### Steps to Reproduce

```js
const container = new PIXI.Container()
container.setFromMatrix(
    new PIXI.Matrix().scale(78, 78)
)

const ellipseGraphics = new PIXI.Graphics().ellipse(3, 3, 6, 6).stroke();

container.addChild(ellipseGraphics)
```

### Environment

- **`pixi.js` version**: *8.1.0*
- **Browser & Version**: *Chrome 124.*
- **OS & Version**: *MacOS 14.4.1*
- **Running Example**: *https://pixiplayground.com/#/edit/CiNBzQRpaPgwI6bQkAsRU*

### Possible Solution

Maybe we should generate more segments when scale is large.

**Comment by bigtimebuddy** [comment]
This is working as intended. All curves need to be triangulated like this. But Pixi also draws curves adaptively (based on how large the _curve_ is). The suggestion here is either to 1) draw the curve at the largest size and scale down, or 2) adjust the adaptive curve settings to your desired needs. There is performance cost in rendering too many points which is why we don't do it by default.

**Comment by F-star** [comment]
OK, thank you!
