### ISSUE TITLE
Bug: Invisible containers, in some cases, when using Filter + Extract (v8.x)

### ISSUE THREAD

**Issue by LazeKer** [pixijs/pixijs#10594]
### Current Behavior

Containers become invisible (not rendered) when you combine: 
- An offscreen parent container
- At least a filter
- Extracting with the renderer (pixel/image/canvas/etc)

### Expected Behavior

Containers should stay visible with the filter effect after any kind of extraction

### Steps to Reproduce

PixiPlayground link: [minimal reproductrion](https://pixijs.com/8.x/playground?state=eyJmaWxlcyI6eyIvc3JjL2luZGV4LmpzIjp7ImNvZGUiOiJpbXBvcnQgeyBBcHBsaWNhdGlvbiwgQ29udGFpbmVyLCBHcmFwaGljcywgQmx1ckZpbHRlciB9IGZyb20gJ3BpeGkuanMnO1xuXG4oYXN5bmMgKCkgPT4ge1xuICAgIC8vIENyZWF0ZSBhIG5ldyBhcHBsaWNhdGlvblxuICAgIGNvbnN0IGFwcCA9IG5ldyBBcHBsaWNhdGlvbigpO1xuXG4gICAgLy8gSW5pdGlhbGl6ZSB0aGUgYXBwbGljYXRpb25cbiAgICBhd2FpdCBhcHAuaW5pdCh7IGJhY2tncm91bmQ6ICcjMTA5OWJiJywgcmVzaXplVG86IHdpbmRvdyB9KTtcblxuICAgIC8vIEFwcGVuZCB0aGUgYXBwbGljYXRpb24gY2FudmFzIHRvIHRoZSBkb2N1bWVudCBib2R5XG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChhcHAuY2FudmFzKTtcblxuICAgIC8vIENyZWF0ZSBncmFwaGljXG5cdGNvbnN0IHNxdWFyZSA9IG5ldyBHcmFwaGljcygpXG5cdHNxdWFyZS5yZWN0KDAsIDAsIDUwLCA1MClcblx0c3F1YXJlLmZpbGwoMHg1NWZmNTUpXG4gICAgc3F1YXJlLnggPSAxNTBcbiAgICBzcXVhcmUueSA9IDUwXG4gICAgc3F1YXJlLmZpbHRlcnMgPSBuZXcgQmx1ckZpbHRlcigpXG5cbiAgICAvLyBBZGQgXCJvZmZzY3JlZW5cIiBjb250YWluZXJcbiAgICBjb25zdCBjb250YWluZXIgPSBuZXcgQ29udGFpbmVyKClcbiAgICBjb250YWluZXIueCA9IC0xMDBcblxuICAgIC8vIEFkZCB0byBzdGFnZVxuXHRjb250YWluZXIuYWRkQ2hpbGQoc3F1YXJlKVxuXHRhcHAuc3RhZ2UuYWRkQ2hpbGQoY29udGFpbmVyKVxuXG4gICAgLy8gRXh0cmFjdCBwaXhlbCAoZm9yIHRlc3QgcHVycG9zZSlcbiAgICBzZXRUaW1lb3V0KCgpID0%2BIHtcblx0ICAgIGFwcC5yZW5kZXJlci5leHRyYWN0LnBpeGVscyhzcXVhcmUpXG4gICAgfSwgMjAwMClcbn0pKCk7XG4ifSwiL3NyYy9zdHlsZXMuY3NzIjp7ImNvZGUiOiJib2R5IHsgbWFyZ2luOiAwOyBvdmVyZmxvdzogaGlkZGVuOyB9In0sIi9pbmRleC5odG1sIjp7ImNvZGUiOiJcbjwhRE9DVFlQRSBodG1sPlxuICA8aHRtbD5cbiAgPGhlYWQ%2BXG4gIDx0aXRsZT5QaXhpSlMgUGxheWdyb3VuZDwvdGl0bGU%2BXG4gIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiIC8%2BXG4gIDxsaW5rIHJlbD1cInN0eWxlc2hlZXRcIiBocmVmPVwic3JjL3N0eWxlcy5jc3NcIj5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2NyaXB0IHNyYz1cInNyYy9pbmRleC5qc1wiPjwvc2NyaXB0PlxuPC9ib2R5PlxuPC9odG1sPiJ9LCIvcGFja2FnZS5qc29uIjp7ImNvZGUiOiJ7XG4gIFwic2NyaXB0c1wiOiB7XG4gICAgXCJzdGFydFwiOiBcInBhcmNlbCBpbmRleC5odG1sIC0tb3BlblwiLFxuICAgIFwiYnVpbGRcIjogXCJwYXJjZWwgYnVpbGQgaW5kZXguaHRtbFwiXG4gIH0sXG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcInBpeGkuanNcIjogXCI4LjEuNVwiXG4gIH0sXG4gIFwiZGV2RGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcInBhcmNlbC1idW5kbGVyXCI6IFwiXjEuNi4xXCIsXG4gICAgXCJAYmFiZWwvY29yZVwiOiBcIl43LjIxLjNcIixcbiAgICBcIkBiYWJlbC9wbHVnaW4tcHJvcG9zYWwtY2xhc3MtcHJvcGVydGllc1wiOiBcIl43LjEwLjFcIlxuICB9LFxuICBcIm1haW5cIjogXCIvaW5kZXguaHRtbFwiXG59In0sIi8uYmFiZWxyYyI6eyJjb2RlIjoie1xuICBcInByZXNldHNcIjogW1xuICAgIFtcbiAgICAgIFwiQGJhYmVsL3ByZXNldC1lbnZcIixcbiAgICAgIHtcbiAgICAgICAgXCJ1c2VCdWlsdEluc1wiOiBcImVudHJ5XCIsXG4gICAgICAgIFwiY29yZWpzXCI6IFwiMy4yOVwiLFxuICAgICAgICBcInRhcmdldHNcIjogXCJsYXN0IDIgY2hyb21lIHZlcnNpb25zXCJcbiAgICAgIH1cbiAgICBdXG4gIF0sXG4gIFwicGx1Z2luc1wiOiBbXG4gICAgXCJAYmFiZWwvcGx1Z2luLXByb3Bvc2FsLWNsYXNzLXByb3BlcnRpZXNcIlxuICBdXG59In0sIi9zYW5kYm94LmNvbmZpZy5qc29uIjp7ImNvZGUiOiJ7XG4gICAgICAgICAgICAgICAgXCJpbmZpbml0ZUxvb3BQcm90ZWN0aW9uXCI6IGZhbHNlXG4gICAgICAgICAgICB9In19LCJ2aXNpYmxlRmlsZXMiOlsiL3NyYy9pbmRleC5qcyJdLCJhY3RpdmVGaWxlIjoiL3NyYy9pbmRleC5qcyJ9&exampleId=custom)

The example contains the tree steps: 
- An offscreen parent container
```ts
container.x = -100
```
- At least a filter
```ts
square.filters = new BlurFilter()
```
- Extracting with the renderer (in the example, after 2s)
```ts
app.renderer.extract.pixels(square)
```

### Environment

- **`pixi.js` version**: > 8.0
- **Browser & Version**: Chrome/Firefox
- **OS & Version**: Windows 11
- **Running Example**: [minimal reproductrion](https://pixijs.com/8.x/playground?state=eyJmaWxlcyI6eyIvc3JjL2luZGV4LmpzIjp7ImNvZGUiOiJpbXBvcnQgeyBBcHBsaWNhdGlvbiwgQ29udGFpbmVyLCBHcmFwaGljcywgQmx1ckZpbHRlciB9IGZyb20gJ3BpeGkuanMnO1xuXG4oYXN5bmMgKCkgPT4ge1xuICAgIC8vIENyZWF0ZSBhIG5ldyBhcHBsaWNhdGlvblxuICAgIGNvbnN0IGFwcCA9IG5ldyBBcHBsaWNhdGlvbigpO1xuXG4gICAgLy8gSW5pdGlhbGl6ZSB0aGUgYXBwbGljYXRpb25cbiAgICBhd2FpdCBhcHAuaW5pdCh7IGJhY2tncm91bmQ6ICcjMTA5OWJiJywgcmVzaXplVG86IHdpbmRvdyB9KTtcblxuICAgIC8vIEFwcGVuZCB0aGUgYXBwbGljYXRpb24gY2FudmFzIHRvIHRoZSBkb2N1bWVudCBib2R5XG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChhcHAuY2FudmFzKTtcblxuICAgIC8vIENyZWF0ZSBncmFwaGljXG5cdGNvbnN0IHNxdWFyZSA9IG5ldyBHcmFwaGljcygpXG5cdHNxdWFyZS5yZWN0KDAsIDAsIDUwLCA1MClcblx0c3F1YXJlLmZpbGwoMHg1NWZmNTUpXG4gICAgc3F1YXJlLnggPSAxNTBcbiAgICBzcXVhcmUueSA9IDUwXG4gICAgc3F1YXJlLmZpbHRlcnMgPSBuZXcgQmx1ckZpbHRlcigpXG5cbiAgICAvLyBBZGQgXCJvZmZzY3JlZW5cIiBjb250YWluZXJcbiAgICBjb25zdCBjb250YWluZXIgPSBuZXcgQ29udGFpbmVyKClcbiAgICBjb250YWluZXIueCA9IC0xMDBcblxuICAgIC8vIEFkZCB0byBzdGFnZVxuXHRjb250YWluZXIuYWRkQ2hpbGQoc3F1YXJlKVxuXHRhcHAuc3RhZ2UuYWRkQ2hpbGQoY29udGFpbmVyKVxuXG4gICAgLy8gRXh0cmFjdCBwaXhlbCAoZm9yIHRlc3QgcHVycG9zZSlcbiAgICBzZXRUaW1lb3V0KCgpID0%2BIHtcblx0ICAgIGFwcC5yZW5kZXJlci5leHRyYWN0LnBpeGVscyhzcXVhcmUpXG4gICAgfSwgMjAwMClcbn0pKCk7XG4ifSwiL3NyYy9zdHlsZXMuY3NzIjp7ImNvZGUiOiJib2R5IHsgbWFyZ2luOiAwOyBvdmVyZmxvdzogaGlkZGVuOyB9In0sIi9pbmRleC5odG1sIjp7ImNvZGUiOiJcbjwhRE9DVFlQRSBodG1sPlxuICA8aHRtbD5cbiAgPGhlYWQ%2BXG4gIDx0aXRsZT5QaXhpSlMgUGxheWdyb3VuZDwvdGl0bGU%2BXG4gIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiIC8%2BXG4gIDxsaW5rIHJlbD1cInN0eWxlc2hlZXRcIiBocmVmPVwic3JjL3N0eWxlcy5jc3NcIj5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2NyaXB0IHNyYz1cInNyYy9pbmRleC5qc1wiPjwvc2NyaXB0PlxuPC9ib2R5PlxuPC9odG1sPiJ9LCIvcGFja2FnZS5qc29uIjp7ImNvZGUiOiJ7XG4gIFwic2NyaXB0c1wiOiB7XG4gICAgXCJzdGFydFwiOiBcInBhcmNlbCBpbmRleC5odG1sIC0tb3BlblwiLFxuICAgIFwiYnVpbGRcIjogXCJwYXJjZWwgYnVpbGQgaW5kZXguaHRtbFwiXG4gIH0sXG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcInBpeGkuanNcIjogXCI4LjEuNVwiXG4gIH0sXG4gIFwiZGV2RGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcInBhcmNlbC1idW5kbGVyXCI6IFwiXjEuNi4xXCIsXG4gICAgXCJAYmFiZWwvY29yZVwiOiBcIl43LjIxLjNcIixcbiAgICBcIkBiYWJlbC9wbHVnaW4tcHJvcG9zYWwtY2xhc3MtcHJvcGVydGllc1wiOiBcIl43LjEwLjFcIlxuICB9LFxuICBcIm1haW5cIjogXCIvaW5kZXguaHRtbFwiXG59In0sIi8uYmFiZWxyYyI6eyJjb2RlIjoie1xuICBcInByZXNldHNcIjogW1xuICAgIFtcbiAgICAgIFwiQGJhYmVsL3ByZXNldC1lbnZcIixcbiAgICAgIHtcbiAgICAgICAgXCJ1c2VCdWlsdEluc1wiOiBcImVudHJ5XCIsXG4gICAgICAgIFwiY29yZWpzXCI6IFwiMy4yOVwiLFxuICAgICAgICBcInRhcmdldHNcIjogXCJsYXN0IDIgY2hyb21lIHZlcnNpb25zXCJcbiAgICAgIH1cbiAgICBdXG4gIF0sXG4gIFwicGx1Z2luc1wiOiBbXG4gICAgXCJAYmFiZWwvcGx1Z2luLXByb3Bvc2FsLWNsYXNzLXByb3BlcnRpZXNcIlxuICBdXG59In0sIi9zYW5kYm94LmNvbmZpZy5qc29uIjp7ImNvZGUiOiJ7XG4gICAgICAgICAgICAgICAgXCJpbmZpbml0ZUxvb3BQcm90ZWN0aW9uXCI6IGZhbHNlXG4gICAgICAgICAgICB9In19LCJ2aXNpYmxlRmlsZXMiOlsiL3NyYy9pbmRleC5qcyJdLCJhY3RpdmVGaWxlIjoiL3NyYy9pbmRleC5qcyJ9&exampleId=custom)

**Comment by GoodBoyDigital** [comment]
heya! will take a look at this one soon - for now there is a [workaround](https://pixijs.com/8.x/playground?state=eyJmaWxlcyI6eyIvc3JjL2luZGV4LmpzIjp7ImNvZGUiOiJpbXBvcnQgeyBBcHBsaWNhdGlvbiwgQ29udGFpbmVyLCBHcmFwaGljcywgQmx1ckZpbHRlciB9IGZyb20gJ3BpeGkuanMnO1xuXG4oYXN5bmMgKCkgPT4ge1xuICAgIC8vIENyZWF0ZSBhIG5ldyBhcHBsaWNhdGlvblxuICAgIGNvbnN0IGFwcCA9IG5ldyBBcHBsaWNhdGlvbigpO1xuXG4gICAgLy8gSW5pdGlhbGl6ZSB0aGUgYXBwbGljYXRpb25cbiAgICBhd2FpdCBhcHAuaW5pdCh7IGJhY2tncm91bmQ6ICcjMTA5OWJiJywgcmVzaXplVG86IHdpbmRvdyB9KTtcblxuICAgIC8vIEFwcGVuZCB0aGUgYXBwbGljYXRpb24gY2FudmFzIHRvIHRoZSBkb2N1bWVudCBib2R5XG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChhcHAuY2FudmFzKTtcblxuY29uc3Qgd3JhcHBlckNvbnRhaW5lciA9IG5ldyBDb250YWluZXIoKTtcblxuICAgIC8vIENyZWF0ZSBncmFwaGljXG5cdGNvbnN0IHNxdWFyZSA9IG5ldyBHcmFwaGljcygpXG5cdHNxdWFyZS5yZWN0KDAsIDAsIDUwLCA1MClcblx0c3F1YXJlLmZpbGwoMHg1NWZmNTUpXG4gICAgc3F1YXJlLnggPSAxNTBcbiAgICBzcXVhcmUueSA9IDUwXG4gICAgc3F1YXJlLmZpbHRlcnMgPSBuZXcgQmx1ckZpbHRlcigpXG5cbiAgICAvLyBBZGQgXCJvZmZzY3JlZW5cIiBjb250YWluZXJcbiAgICBjb25zdCBjb250YWluZXIgPSBuZXcgQ29udGFpbmVyKClcbiAgICBjb250YWluZXIueCA9IC0xMDBcblxuICAgIHdyYXBwZXJDb250YWluZXIuYWRkQ2hpbGQoc3F1YXJlKTtcblxuICAgIC8vIEFkZCB0byBzdGFnZVxuXHRjb250YWluZXIuYWRkQ2hpbGQod3JhcHBlckNvbnRhaW5lcilcblx0YXBwLnN0YWdlLmFkZENoaWxkKGNvbnRhaW5lcilcblxuICAgIC8vIEV4dHJhY3QgcGl4ZWwgKGZvciB0ZXN0IHB1cnBvc2UpXG4gICAgc2V0VGltZW91dCgoKSA9PiB7XG5cdCAgICBhcHAucmVuZGVyZXIuZXh0cmFjdC5waXhlbHMod3JhcHBlckNvbnRhaW5lcilcbiAgICB9LCAyMDAwKVxufSkoKTtcbiJ9LCIvc3JjL3N0eWxlcy5jc3MiOnsiY29kZSI6ImJvZHkgeyBtYXJnaW46IDA7IG92ZXJmbG93OiBoaWRkZW47IH0ifSwiL2luZGV4Lmh0bWwiOnsiY29kZSI6IlxuPCFET0NUWVBFIGh0bWw%2BXG4gIDxodG1sPlxuICA8aGVhZD5cbiAgPHRpdGxlPlBpeGlKUyBQbGF5Z3JvdW5kPC90aXRsZT5cbiAgPG1ldGEgY2hhcnNldD1cIlVURi04XCIgLz5cbiAgPGxpbmsgcmVsPVwic3R5bGVzaGVldFwiIGhyZWY9XCJzcmMvc3R5bGVzLmNzc1wiPlxuPC9oZWFkPlxuPGJvZHk%2BXG4gIDxzY3JpcHQgc3JjPVwic3JjL2luZGV4LmpzXCI%2BPC9zY3JpcHQ%2BXG48L2JvZHk%2BXG48L2h0bWw%2BIn0sIi9wYWNrYWdlLmpzb24iOnsiY29kZSI6IntcbiAgXCJzY3JpcHRzXCI6IHtcbiAgICBcInN0YXJ0XCI6IFwicGFyY2VsIGluZGV4Lmh0bWwgLS1vcGVuXCIsXG4gICAgXCJidWlsZFwiOiBcInBhcmNlbCBidWlsZCBpbmRleC5odG1sXCJcbiAgfSxcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwicGl4aS5qc1wiOiBcIjguMS41XCJcbiAgfSxcbiAgXCJkZXZEZXBlbmRlbmNpZXNcIjoge1xuICAgIFwicGFyY2VsLWJ1bmRsZXJcIjogXCJeMS42LjFcIixcbiAgICBcIkBiYWJlbC9jb3JlXCI6IFwiXjcuMjEuM1wiLFxuICAgIFwiQGJhYmVsL3BsdWdpbi1wcm9wb3NhbC1jbGFzcy1wcm9wZXJ0aWVzXCI6IFwiXjcuMTAuMVwiXG4gIH0sXG4gIFwibWFpblwiOiBcIi9pbmRleC5odG1sXCJcbn0ifSwiLy5iYWJlbHJjIjp7ImNvZGUiOiJ7XG4gIFwicHJlc2V0c1wiOiBbXG4gICAgW1xuICAgICAgXCJAYmFiZWwvcHJlc2V0LWVudlwiLFxuICAgICAge1xuICAgICAgICBcInVzZUJ1aWx0SW5zXCI6IFwiZW50cnlcIixcbiAgICAgICAgXCJjb3JlanNcIjogXCIzLjI5XCIsXG4gICAgICAgIFwidGFyZ2V0c1wiOiBcImxhc3QgMiBjaHJvbWUgdmVyc2lvbnNcIlxuICAgICAgfVxuICAgIF1cbiAgXSxcbiAgXCJwbHVnaW5zXCI6IFtcbiAgICBcIkBiYWJlbC9wbHVnaW4tcHJvcG9zYWwtY2xhc3MtcHJvcGVydGllc1wiXG4gIF1cbn0ifSwiL3NhbmRib3guY29uZmlnLmpzb24iOnsiY29kZSI6IntcbiAgICAgICAgICAgICAgICBcImluZmluaXRlTG9vcFByb3RlY3Rpb25cIjogZmFsc2VcbiAgICAgICAgICAgIH0ifX0sInZpc2libGVGaWxlcyI6WyIvc3JjL2luZGV4LmpzIl0sImFjdGl2ZUZpbGUiOiIvc3JjL2luZGV4LmpzIn0%3D) of adding the thing you want to extract to a container and extracting that, rather than the sprite. Not perfect, but should unblock ya in the short term i hope!

**Comment by yungzhu** [comment]
I also encountered this problem

**Comment by GoodBoyDigital** [comment]
heya! I know what this is now :)
this should fix the resolution issue: https://github.com/pixijs/pixijs/pull/11117
the final issue is todo with the bounds of the mask being mishandled when being rendered in a filter, in a render group. Will have a fix soon though!
