### ISSUE TITLE
Bug: NineSliceSprite does not handle width/scale the same as sprite

### ISSUE THREAD

**Issue by rory-pickering** [pixijs/pixijs#11011]
### Current Behavior

If a sprite is set to .5 scale and then you set with to 100px it will be 100px wide
if a NineSliceSprite is set to .5 scale and then you set the width to 100px it will be 50px wide

### Expected Behavior

They should be handled the same.

### Steps to Reproduce

https://codepen.io/rorypicko1992/pen/eYqGKPK

### Environment

- **`pixi.js`: 8.5.1
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by GoodBoyDigital** [comment]
heya, I can see how this may cause confusion.

Essentially sprite width and height are scale modifiers
Where as with NineSliceSprite with and height actually change the size of the geometry (rather than the modify the scale)

So setting the scale of a NineSliceSprite is dfferent than setting the width, where as setting the scale of a sprite is essentially modifying the width?

Let me know if that makes sense :P

**Comment by rory-pickering** [comment]
Ok, yeah that makes sense! Thanks for taking the time to respond.
