### ISSUE TITLE
NineSlicePlane + Spritesheet = Texture Bleeding

### ISSUE THREAD

**Issue by Mwni** [pixijs/pixijs#6451]
Checking back on #3671 , it was said there will be some sort of solution on v5 for this.
Unfortunately the textures of the surrounding patches are still being displayed.

**Comment by ivanpopelyshev** [comment]
Oh, right, that's because I didnt add that shader to vanilla pixi :( and i didnt move it from pixi-heaven v4 to v5, so no, you have to wait or make your custom shader for mesh that clamps texture frame, pass that texture frame through uniform the same way i pass it in TilingSprite.

**Comment by ivanpopelyshev** [comment]
Thanks for remininding this though!

**Comment by ivanpopelyshev** [comment]
I think heaven meshes is the last thing that has to be moved from v4 to v5 so we'll have this feature soon.

**Comment by lunarraid** [comment]
Is this something that is still being worked on?

**Comment by bigtimebuddy** [comment]
Question for @ivanpopelyshev

**Comment by lunarraid** [comment]
I'm still experiencing this behavior, and I think it's the only blocker for switching out our renderer for pixi.js. There are workarounds, but since most of our UI are sliced assets and our spriter tool is baked into our systems, it's a major hurdle.

**Comment by lunarraid** [comment]
Playing with this more, it looks like if we apply the same trim math from the Sprite class to this class, the NineSlicePlane works correctly.

**Comment by md5crypt** [comment]
Wrote a class extending NineSlicePlane with a fix for this issue: https://gist.github.com/md5crypt/29ed77d14231422370dc8f179e0b42d5
The fix is not perfect as it will not work correctly if the slicing region is larger then zero and smaller then the trimming region, but that's an edge case I don't really care about. There is probably some super simple solution for this that will make me feel stupid but I don't really have more time to waste on this. Hope this comment will save someone the 3h I put into this.
