### ISSUE TITLE
cacheAsBitmap for a container with a mask (5.3.1+)

### ISSUE THREAD

**Issue by playmoredevelop** [pixijs/pixijs#6792]
Hi everyone!

In version 5.3.2, I get strange behavior of the cacheAsBitmap method, if there is a container with a mask inside, and the scale of this container is **not equal to 1**
In version 5.3.0 everything **works** fine

I made a couple of examples:
[cacheAsBitmap with 5.3.2](https://jsfiddle.net/p1aymore/t3L7wskp/)
[cacheAsBitmap with 5.3.0](https://jsfiddle.net/p1aymore/5m81tfb7/)

just click on stage to cache the container

**Comment by antag0n1st** [comment]
I have a similar problem , but mine is a bit different.
When I load an image from the web , and try to cache it ( inside a container with a mask , in order to create a nice circle bordered image ) the image simply disappears , but this is not the case if the image is already loaded and the browser is reading it from its own cache.
![circle-photos](https://user-images.githubusercontent.com/1247110/92215080-90322f80-ee94-11ea-9582-8bdbfe0538bb.gif)

**Comment by IljaDaderko** [comment]
Was able to replicate this in same conditions

1. Create sprite, size it and place into container
2. Add mask to the container
3. add `cacheAsBitmap` to container

It seems that all sprites now return to their original size and don't respect previously set width/height settings.

**Comment by adi** [comment]
I'm not sure if it is best to create a new issue or not but I just discovered that `cacheAsBitmap` on a container sets the alpha of that container to 1 and disregards the previous alpha. It does that exactly once, most probably when caching. Setting the alpha again after the initial cache works as expected. This looks very similar in behavior to this issue although it refers to another property.

**Comment by lunarraid** [comment]
I was just about to open an issue about this exact thing since I'm dealing with issues setting alpha values on cacheAsBitmap sprites, but will follow this issue to see where this goes. The cache doesn't seem to happen until the first render, so if you read the alpha value immediately after setting the flag, the value is correct, but a later read shows it's been set back to 1.

**Comment by ivanpopelyshev** [comment]
@antag0n1st 

Its one of basic issues that everyone encounters in PixiJS. 
Basically, if you use texture onload thingy:

```
const tex = Texture.from('myUrl');

if (tex.baseTexture.valid) {
   // already loaded!
} else {
   tex.baseTexture.on('loaded', () => {
      //loaded a bit later
   });
}
```

Its not particularly a Pixi problem, this behaviour is introduced in html `Image` element (onload, complete).

In v5, `Texture.fromUrl()` allows to use promises

```js
const promise = Texture.fromUrl('myUrl');

promise.then((texture) => {
   //use the texture
});
```

**Comment by ivanpopelyshev** [comment]
@lunarraid

Yes, alpha propagates wrongly in cacheAsBitmap, its known for a long time, was mentioned countless threads and so far no one submitted PR to fix it. For my projects I use custom tree that can propagate and "stop" things from propagating in case there's something like cache. Its not easy solution so I cannot share it.

**Comment by ivanpopelyshev** [comment]
@lunarraid if you really need that thing - create an issue and be ready to provide feedback when its needed.
