### ISSUE TITLE
Allow events to continue propogating to siblings

### ISSUE THREAD

**Issue by luxaritas** [pixijs/pixijs#6926]
Example situation: two NPC sprites which are siblings, where clicks should register on both sprites.

#2921 was originally tracking this before it was locked for inactivity, and [there was a proposal workaround for this](https://github.com/pixijs/pixi.js/issues/2921#issuecomment-493801249) (which I have implemented similarly), however it is not ideal, since it relies on using private properties of InteractionManager.

**Comment by luxaritas** [comment]
The specific implementation I used, which just re-ran the relevant processInteractive call with the previous DisplayObject's interactive property set to false: https://github.com/eternagame/EternaJS/blob/6a7af62b06da16e0eb07ca6fd106cb26e7e166cd/src/flashbang/input/PointerCapture.ts#L100

**Comment by luxaritas** [comment]
Still relevant. Any thoughts about something like a function on the interaction manager that takes an event as a parameter, and does the same operation that I do in the example above? I'd be willing to attempt a PR for that

**Comment by bigtimebuddy** [comment]
This is a limitation of the interaction manager. We have gotten many requests over the years to add things like bubbling and capture to the events, but have not mostly for performance reasons but also because the interaction system is difficult to maintain. @SukantPal has worked on a proposal to redo this for our next major release (likely v7). There is a discussion #7071 seeks to add these DOM-like behaviors. 

All that is to say, I'm not sure there's an easy solution for you now other than maybe using hitTest to manually check elements under the pointer.

**Comment by luxaritas** [comment]
This should probably stay open for tracking unless #7071 supersedes

**Comment by bigtimebuddy** [comment]
Thanks for following up @luxaritas. I'm going to close this issue as @SukantPal has implemented a killer new interaction package called `@pixi/events` that has support for a variety of DOM-like features. It'll be included as an optional package in the 6.1 release. [Here](https://pixijs.io/examples/#/events/click.js) are some examples that use the events library.

**Comment by luxaritas** [comment]
Awesome! Can't wait to try it

**Comment by ivanpopelyshev** [comment]
@luxaritas you can enable it in v6 by adding https://github.com/pixijs/pixijs/tree/dev/packages/events into your bundle `@pixijs/events`, i believe
