### ISSUE TITLE
setCursorMode actually does not work

### ISSUE THREAD

**Issue by WishQi** [pixijs/pixijs#7007]
I have set the cursor styles like this:
```
app.renderer.plugins.interaction.cursorStyles = {
      ...this.app.renderer.plugins.interaction.cursorStyles,
      [CursorMode.default]: 'url(/public/cursor/default.png), auto',
      [CursorMode.frame]: 'url(/public/cursor/frame.png), auto',
      [CursorMode.rect]: 'url(/public/cursor/rect.png), auto',
      [CursorMode.text]: 'url(/public/cursor/text.png), auto',
      [CursorMode.move]: 'url(/public/cursor/move.png), auto',
};
```
And I call the setCursorMode:
```
interaction.setCursorMode(cursorMode);
```

But it does not work. So I tried to debug, and I found the following code in `InteractionManager.ts`:
```
public update(): void
    {
        this.cursor = null;
        ......
        this.setCursorMode(this.cursor);
    }
```

So actually the cursorMode will always be `default`.

Is this a bug? If it is not, I want to know the reason for the code.

**Comment by bigtimebuddy** [comment]
This is probably an @andrewstart question. Thoughts?

**Comment by andrewstart** [comment]
The most important part of the update method is in that `.....`:
```javascript
public update(): void
    {
        // clear the desired cursor mode, because if we don't mouse over anything we want to return to the default
        this.cursor = null;
        // now we run through the display list to see what the mouse is over in order to determine what the cursor should be
        // That process sets this.cursor
        ......
        // once we have determined what interactive object the mouse is over, and thus what cursor that object wants to be used,
        // we set the cursor mode
        this.setCursorMode(this.cursor);
    }
```
In general you shouldn't need to call `setCursorMode()` yourself because it is calculated automatically when the mouse moves. Instead, you want to set the `cursor` property on display objects that should trigger specific cursors. If you do want to manually control the cursor at all times, instead you should clear the `cursorStyles` dictionary so that the InteractionManager won't attempt to set any css (and then don't use the `cursor` property on display objects at all).

**Comment by WishQi** [comment]
@andrewstart If I clear the cursorStyles, how can I change the cursor style? I do not want use a sprite to replace the cursor.

**Comment by andrewstart** [comment]
If you clear the cursorStyles (or set each item to `null`), then the InteractionManager just won't do anything with the cursors on mouseover, allowing you to set the style of the canvas directly at any time that you want, if that's what you were going for. Again, you probably don't need to do that because you can just set and update the `cursor` property on relevant display objects.

**Comment by lsqlebai** [comment]
```
public update(): void
    {
        // clear the desired cursor mode, because if we don't mouse over anything we want to return to the default
        this.cursor = null;
        // now we run through the display list to see what the mouse is over in order to determine what the cursor should be
        // That process sets this.cursor
        ......
        // once we have determined what interactive object the mouse is over, and thus what cursor that object wants to be used,
        // we set the cursor mode
        this.setCursorMode(this.cursor);
    }
```

@andrewstart 
when the update function execution. this.cursor will be always  null。 So cursorMode must be always null???

**Comment by andrewstart** [comment]
In the code that is replaced by `......` in that snippet, `this.cursor` is set when an object is moused over. On one of your display objects, set `myObj.interactive = true` and `myObj.cursor = CursorMode.frame` and you should see a frame cursor appear when you mouse over that object.
