### ISSUE TITLE
5.3.3 Changing filter.resolution does not appear to modify the resolution of the filter

### ISSUE THREAD

**Issue by liamegan** [pixijs/pixijs#7014]
Creating a new filter and immediately modifying the resolution does not appear to effect the resolution of the rendered filter, see:
https://codesandbox.io/s/wispy-moon-u7e0j?file=/src/index.js

See:
```
  // Build the filter
  const filter = new PIXI.Filter(null, fragment, {
    time: -400.5, // The time uniform.
    offset: [viewport.center.x, viewport.center.y * -1], // The offset of the viewport, measured from the center
    dimensions: [window.innerWidth, window.innerHeight], // The window dimensions.
    zoom: 1, // The viewport zoom factor
    t_noise: noise_tex // The noise texture, for pseudorandom number generation
  });
  filter.resolution = 0.1;
```

Expected behaviour: As I'm lowering the resolution so much (as a test) I would expect the background to be rendered quite blurry.

**Comment by ivanpopelyshev** [comment]
what filter does:
1. it renders container into temporary renderTexture
2. it renders renderTexture to screen using filter shader.

resolution affects `renderTexture.resolution`
in your case , renderTexture is not used. at all. no `uSampler` usage, i dont see it. It should be mesh-shader rather than filter https://pixijs.io/examples/#/mesh-and-shaders/triangle-textured.js And even then you wont get blurry stuff.

To get blurry stuff, you have to use that shader whether its filter or mesh-shader form on a surface that already has resolution=0.1. For example, there can be one more filter above, AlphaFilter, with resolution=0.1

**Comment by liamegan** [comment]
I see. I was excited when I came across the resolution setting as I thought that there might be a framebuffer running behind the scenes that allows the filter to first render to a reduced resolution copy for the purposes of optimisation.

**Comment by ivanpopelyshev** [comment]
Well it renders reduced resolution copy of ... nothing ) 
fragment shader is called per-pixel on output framebuffer, not on input.
