### ISSUE TITLE
pixijs v5.x use mask can't app.renderer.extract.base64

### ISSUE THREAD

**Issue by a6965921** [pixijs/pixijs#7052]
pixijs v5.x use mask can't app.renderer.extract.base64
`` const app = new PIXI.Application();
    document.body.appendChild(app.view);

    var imgURL = "/moban/images/share.jpg";
    //加载图像，加载完成后执行setup函数 
    PIXI.loader.add(imgURL).load(setup);

    function setup() {
        var bunny1 = PIXI.Sprite.from('/moban/images/share.jpg');
        // bunny1.width = 330;
        // bunny1.height = 360;
        bunny1.name = 'sharejpg';
        bunny1.x = 192;
        bunny1.y = 22;
        app.stage.addChild(bunny1);

     
const graphics = new PIXI.Graphics();

// Rectangle
graphics.beginFill(0xDE3249);
graphics.drawRect(150, 50, 100, 100);
graphics.endFill();
app.stage.addChild(graphics);
     bunny1.mask=graphics;

   var huayuanbas64 = app.renderer.extract.base64(bunny1);
       console.log(huayuanbas64);     
    }

**Comment by ivanpopelyshev** [comment]
Graphics transform is not updated there. usually its updated in `render`, but its only rendering `bunny1` here. However its not a problem because graphics doesnt have any changes in transform

Work of masks/filters inside `extract` or `generateTexture` is full of bugs. We fixed it countless times, and still there are cases when it doesnt work. The only good way to solve issue for you is to do everything manually. Extract/generateTexture are heavy operation, you should look their source code. Possible workarounds:
1. wrap bunny1 in another container adn try it
2. dont use `extract` directly. Render bunny into renderTExture that you create manually, then `extract` from the renderTexture. Dont forget to destroy it afterwards.

Also, why do you need to extract bunny? Maybe there are alternatives. For example, for pixel-perfect interaction there is https://github.com/pixijs/pixi.js/wiki/v5-Hacks#pixel-perfect-interaction
