### ISSUE TITLE
branch v5.3.x init error

### ISSUE THREAD

**Issue by tomleader** [pixijs/pixijs#7168]
### Expected Behavior
check out the v5.3.x branch 
then run `npm i` 
expected normal 

### Current Behavior
Errors occur when running npm i 

npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for pixi.js-monorepo@: wanted: {"node":"^10","yarn":"please-use-npm","npm":"^6"} (current: {"node":"14.15.4","npm":"6.14.11"})
npm ERR! notsup Not compatible with your version of node/npm: pixi.js-monorepo@
npm ERR! notsup Not compatible with your version of node/npm: pixi.js-monorepo@
npm ERR! notsup Required: {"node":"^10","yarn":"please-use-npm","npm":"^6"}
npm ERR! notsup Actual:   {"npm":"6.14.11","node":"14.15.4"}

### Possible Solution
Maybe the version/engine check should modify..
### Steps to Reproduce
1. check out pixi.js
2. switch to v5.3.x branches
3. run npm i
### Environment
- **`pixi.js` version**:v5.3.x
- **Browser & Version**: 
- **OS & Version**: mac os 10.14.6
- **Running Example**:

**Comment by staff0rd** [comment]
Your node version appears to be one pixi does not build against. I had a similar issue earlier in the year with node 12, but it appears [node 12 is now supported](https://github.com/pixijs/pixi.js/commit/54665ecebe676bd0d89e7ceadabb1badd89c1cbb).

I pondered whether the README could be updated to to state this - I've raised no such PR because I never would have read the README anyway :D

**Comment by bigtimebuddy** [comment]
On 5.3.x we are still locked to node 10 because of an issue with JSDoc. We have fixed this probable in dev/main. To build 5.3.x you need to install node 10 or use nvm to switch.

These engine requirements are correct.
