### ISSUE TITLE
PIXI requires unsafe CSP

### ISSUE THREAD

**Issue by rubenlg** [pixijs/pixijs#7324]
### Expected Behavior
PIXI.js works with a strict CSP (e.g. `script-src 'self'`) by default.

### Current Behavior
PIXI.js requires an external module that patches it in order to work with strict CSP (`@pixi/unsafe-eval`). Not being safe by default opens a number of attack vectors on the application of the developer:
* Opens the door to XSS due to PIXI itself. Even if today your use of `new Function` is safe (has anyone conducted a security audit recently?), as code evolves, there is a significant risk that an XSS vulnerability will be introduced by accident.
* A relaxed CSP allowing unsafe eval can't be applied just to PIXI (as far as I know, let me know otherwise), so because of PIXI, the unsafe eval behavior has to be allowed on the entire app. While PIXI engineers can, to some extent, be confident in the security of the PIXI library, you can't be confident about any other code landing on the final application of the developer.

The whole point of CSP is to deal with situations in which you can't reliably ensure the quality of all the sources being pulled into your final application.

### Possible Solution
Make `@pixi/unsafe-eval` the default behavior of PIXI.js, and instead create an external module to make PIXI faster for those devs who need the extra speed **and** know what they are doing. Most likely, the majority of developers won't need the extra speed, but their end users will appreciate the extra security.

### Steps to Reproduce
Add a strict CSP meta tag to your HTML (or a header):
```html
  <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'">
```
Run a PIXI-based application.

### Environment

- **`pixi.js` version**: 5.3.8
- **Browser & Version**: Chrome 89
- **OS & Version**: Ubuntu 20.04.2
- **Running Example**: n/a

Related: #5509

**Comment by ivanpopelyshev** [comment]
PixiJS is about performance. If we cant do `new Function()` , it eats away some JS perf.

> Even if today your use of new Function is safe (has anyone conducted a security audit recently?), as code evolves, there is a significant risk that an XSS vulnerability will be introduced by accident.

Security issue in any WebGL backend (chromium for example) is more likely than we introduce XSS here, and all renderers will be affected that way.

I participated in such bugs in chromium bugtracker.

anyway, Welcome to WebGL.

**Comment by SukantPal** [comment]
Yeah, I don't think we'll switch this in the foreseeable future. A long term solution would be to generate uniform uploading functions at compile time.

**Comment by rubenlg** [comment]
Don't get me wrong. I love PIXI. I've been writing raw WebGL pretty much since it came out 10 years ago, and PIXI changed completely the way I write games and especially level editors, allowing me to focus on the app logic rather than fighting the GL state machine. It's comparable to what OpenSceneGraph did to my code back in the 90s, when I could stop writing raw OpenGL for C++. Thanks a lot for your work!

I understand that there is a trade-off between performance and security. My argument is that by default any web library, including PIXI, should favor security by default, especially when the developer has explicitly enabled CSP because they care, and fall back to performance upon conscious choice by the developer.

Right now, whenever a user has a strict CSP, PIXI just doesn't work. The developer gets a helpful message in the console, but all of the sudden, they are forced to choose between installing an extra module that will make their app slower, or relaxing their CSP. Guess what, most junior developers when faced with that dilemma, blindly choose performance, because they are unable to gauge whether the performance degradation matters at all to their app/game, and loosing frames seems like a much more tangible risk than having an XSS bug in their "perfect" app/game code.

**Here is another alternative:**

You already do feature detection in order to show that *use @pixi/unsafe-eval* message. What if instead of failing with that message, you automatically enable safe+slow mode when you detect a disabled eval (maybe with a console warning about performance implications) and run in unsafe+fast mode whenever eval is allowed?

That way, PIXI would always work regardless of the CSP setting, and people without performance issues wouldn't need to worry about it at all. Does that sound like a reasonable trade-off?

**Comment by SukantPal** [comment]
How would we automatically enable safe+slow mode? We'd need thee @pixi/unsafe-eval package available for that, no?

**Comment by rubenlg** [comment]
> How would we automatically enable safe+slow mode? We'd need the @pixi/unsafe-eval package available for that, no?

Yes, the idea would be to merge `@pixi/unsafe-eval` into the pixi core, so it can automatically pick at runtime without having to install extra packages. I imagine it could be similar to the webgl with canvas fallback logic that's built into the pixi.js module already. I understand it's a refactor, not a simple PR moving files around, though.

**Comment by bigtimebuddy** [comment]
This is an interesting idea. Thank @rubenlg. Likely, doing something like this would be a breaking change and will have to wait for the next major version. I'm not opposed to the unsafe-eval fallback.

Before that though, I'd be interested to see an audit of our current code to understand how vulnerable we are. Do you know anyone who would be willing to help?

In general, PixiJS has not been a vector for attacks that we are aware. We haven't had any security related issues that I can remember in recent memory. Even the unsafe-eval package was about support for a specific environment, not patching a specific security issue.

**Comment by SukantPal** [comment]
The canvas fallback isn't included in the pixi.js bundle (only in pixi.js-legacy).

I understand your concern about security - but I'm pretty sure the vulnerability isn't inside PixiJS. Runtime-generated code is used to create optimized functions that upload uniforms. These functions aren't user-content generated.

A strict CSP, as you mentioned, would be to defend against your own application code's vulnerability. That's legit - but I don't think blaming junior devs for dropping the strict CSP & not installing @pixi/unsafe-eval is makes the case. If you're adding a CSP to your HTML, installing an additional fallback module shouldn't be a biggie.

**Comment by ivanpopelyshev** [comment]
The best way how I see it: 

User runs the app in special test mode, and for all created shader it generates code. When user puts the code in his app - it works without unsafe evaluations. Do you know where I took that idea? Its how all non-JS renderers work. But, what is the point of using JS if we dont use its features?

I can name many things in PixiJS that are not suited for production.

I dont see why non-secure abomination like **NPM** is allowed to exist, why the modular joke **ES6 imports** is allowed to pollute world. PixiJS using unsave evaluations is nothing compared to that. We dont depend on many modules in runtime, we surely have some capacity to monitor a few places where security can be put under question.

**Comment by rubenlg** [comment]
Thanks @bigtimebuddy for acknowledging the merit of the idea. 

I admit I don't know who in the open source community can help with the security audit, I have been immersed in the corporate world for the last 10 years, and I'm used to having a team in the company that I can call to audit my designs and/or risky code. There are a few tools out there to do automatic scans, but nothing beats a seasoned security engineer figuring out how to abuse a piece of code. I guess the next best thing is a project developer using an attacker mindset, but you probably already did that.

The riskiest part inside PIXI seems to be `generateUniformsSync`, which is not a lot of code to audit. From a quick glance, it doesn't sanitize uniform group names (the variable `i`). Perhaps that's sanitized elsewhere, or the integration with other parts of the library makes it impossible to forge those with malicious strings at the moment. You probably know that better than me.

As @ivanpopelyshev said, the attack surface is small enough that you can carefully monitor it, and `generateUniformsSync` doesn't seem to change all that often. That doesn't mean the function is and will always be safe, but the probability seems certainly low that it will become a problem, so the ROI of changing it seems also low.

If you all believe that PIXI being safe is enough to keep the current design, in which developers have to install an extra module to keep the library working in tight security environments, feel free to close this issue.

**Comment by qtiki** [comment]
I just ran into this issue as well while upgrading the security of our CDN. One thing I'd like to add to this is that even with the `@pixi/unsafe-eval` package the try/catch detection causes a CSP violation. This is hidden from the console logs but if you use any of the reporting directives, like [report-to](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to), [report-uri](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri), or the [Content-Security-Policy-Report-Only](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only) header this violation will get logged. In essence this means you'll get a violation report from every user loading the app.

I am confident that PIXI's use of `new Function` is pretty much safe but I don't really like that in order to enable that you will basically have to allow unsafe eval for all scripts on your site.

One other option for the future might be the [strict-dynamic](https://www.w3.org/TR/CSP3/#strict-dynamic-usage) directive. That should allow trusted scripts to run arbitrary generated code. The documentation shows an example of the script add a new `<script>` tag dynamically. I'm not 100% sure if that applies to `eval` and `new Function` as well. However this is not supported in some common browsers yet (like Safari) so I guess we'll have to wait and see how it goes.

Also while testing this with the [require-trusted-types-for](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for) header I found out that [Chrome's trusted Function implementation has a bug](https://github.com/w3c/webappsec-trusted-types/wiki/Trusted-Types-for-function-constructor) which causes even more headache for PIXI's  `new Function` usage - in essence it won't work without that workaround even with the `@pixi/unsafe-eval` package.

I think @SukantPal's idea for a long term solutions sounds good - I was thinking of something similar before landing on this issue. This would really make all of this discussion irrelevant since it all boils down to the runtime usage of `new Function`:
> Yeah, I don't think we'll switch this in the foreseeable future. A long term solution would be to generate uniform uploading functions at compile time.

And while I agree in principle with @ivanpopelyshev's comment about using the language features I have to point out that some language features turn out to be mistakes later on and will get deprecated (or blocked by security features):
> But, what is the point of using JS if we dont use its features?

All that said, we will be sticking with the allow `unsafe-eval` CSP directive for now as the world doesn't seem ready for a more secure configuration with PIXI yet. As a fix for the CSP violation reporting spam it would probably make sense to add a "force" parameter to the [unsafe-eval install function](https://github.com/pixijs/pixijs/blob/dev/packages/unsafe-eval/src/install.ts#L9) so the detection can be skipped in scenarios where you know it won't be allowed.

**Comment by bigtimebuddy** [comment]
Great points @qtiki. I'm in favor of removing the try/catch altogether. It doesn't make sense to have the extra check if you're already opted-in to using the package. Should work like a mixin.

**Comment by bigtimebuddy** [comment]
I closed this (maybe prematurely?) mostly because I address the try/catch. Otherwise we do not intend to change our strategy with regard to unsafe-eval. Happy to continue this as a discussion though.

**Comment by lucashfreitas** [comment]
@qtiki came across the same issue. Our website will be under a security audit which will point to the absence of CSP headers. or the unsafe-eval, but I think that's the only way to use Pixi and CSP headers altogether. I'll research a bit more and will post any updates I may find.

Thanks

**Comment by adelriosantiago** [comment]
Hello, any fix for this? Apps made in Electron show this error and its pretty annoying, its either a non-working PIXI or a Warning message on production.

**Comment by olems** [comment]
Note that bundlers like Webpack might include several copies of a package in the final bundle. We found out after a lot of debugging that there were two copies of pixi in the build, but only one got the unsafe-eval fix applied. 

We haven't been able to find why it does this but it can be avoided by adding an alias for pixi in the webpack config file:
```
module.exports = {
  resolve: {
    alias: {
      '@pixi/core': path.join(__dirname, 'node_modules/@pixi/core'),
      'pixi.js': path.join(__dirname, 'node_modules/pixi.js'),
    },
  },
}
```

**Comment by andra961** [comment]
Any news regarding this?I think you can atleast put a warning or make very clear in documentation that Pixi.js requires unsafe csp to work (or to work as fast as advertised).
