### ISSUE TITLE
Native line style leaves 1px gap in bottom-left corner with drawRect

### ISSUE THREAD

**Issue by jimkyndemeyer** [pixijs/pixijs#7385]
### Expected Behavior
drawRect with native true as line style should close the rectangle

### Current Behavior
There is a 1px gap of the rectangle in the bottom-left corner

### Steps to Reproduce
See https://pixiplayground.com/#/edit/C5FLxdkvIdTZS7CQROsdD

### Environment

- **`pixi.js` version**: 6.0.1
- **Browser & Version**: Chrome 89 and Firefox 87
- **OS & Version**: Windows 10
- **Running Example**: https://pixiplayground.com/#/edit/C5FLxdkvIdTZS7CQROsdD

**Comment by SukantPal** [comment]
Those little details!

**Comment by ShukantPal** [comment]
Coming back to this - it looks like normal WebGL behavior. See, the center of the rectangle strokes do not match the center of a pixel in your example. Instead, the strokes are centered at the "border" of pixels. 4 pixels' corners intersect at (0, 0) for example. WebGL has too "choose" which pixel row to draw the lines in - it seems to choose the "bottom" row in. That's why the top stroke doesn't have a gap - it overlaps with the vertical strokes. However, since the bottom stroke shifts down more below it seems to gap. Similarly, the vertical strokes are drawn in the "left" column and that's why the left stroke has a gap.

<img width="223" alt="Screen Shot 2021-07-08 at 12 13 40 AM" src="https://user-images.githubusercontent.com/22450567/124861331-5bde4280-df81-11eb-9579-3c80b57776c8.png">
Rectangle: (x = 1, y = 1, width = 63, height= 63
 - notice how the left stroke is aligned to the canvas left but the top stroke has a gap. That's because the vertical strokes are shifted left but the horizontal strokes are shifted bottom.

You can fix this by two methods:

* Enable antialiasing: WebGL will draw the stroke in 2 pixels but with half alpha.

<img width="206" alt="Screen Shot 2021-07-08 at 12 14 37 AM" src="https://user-images.githubusercontent.com/22450567/124861417-8af4b400-df81-11eb-8af5-914af7fc25ad.png">

Notice how the strokes are now aligned to the grid. Also, the corners have a "T" intersection - like my drawing. This is the because the strokes are now centered on the pixels correctly.

<img width="64" alt="Screen Shot 2021-07-08 at 12 18 00 AM" src="https://user-images.githubusercontent.com/22450567/124861634-f63e8600-df81-11eb-8675-47538ada5263.png">

* Draw rectangles so their stroke is centered on pixel centers. This means drawing (x= 0.5, y= 0.5) + integers:


<img width="210" alt="Screen Shot 2021-07-08 at 12 20 06 AM" src="https://user-images.githubusercontent.com/22450567/124861824-4584b680-df82-11eb-97f5-ed68f2024224.png">

**Comment by jimkyndemeyer** [comment]
Hi,

Thanks for taking another look. I added a `.5` rectangle to the example which appears to be working as expected. I'll take a look at getting that into my app. It's an overlay for selecting layers for editing, so I'd like it to be a crisp 1px line and not anti-aliased.

Still seems odd to me that an API called `drawRect` fails to render a fully formed rectangle given certain inputs? I'm sure there's internal details and complexity I'm not aware of, but leaking this into user space should be avoided if at all possible in my opinion. Is that why the issue was closed and then reopened?

**Comment by ShukantPal** [comment]
It's not that it doesn't form a rectangle - it is just that the edges aren't aligned so it seems like that. If the edges were 10px thick, these 1px shifts would not break the rectangle. PixiJS just passes along the vertices to WebGL and WebGL draws the rectangle - so it isn't a bug in our logic.
