### ISSUE TITLE
 Loader.js:128 Uncaught TypeError: import_mini_signals.default is not a constructor

### ISSUE THREAD

**Issue by Ayfri** [pixijs/pixijs#7431]
I was making a helper library for PIXI, and after some work, I wanted to try the features but got this error every time I try to create an application.

### Expected Behavior
No error.

### Current Behavior
Getting a weird error.
```ts
Loader.js:128 Uncaught TypeError: import_mini_signals.default is not a constructor
    at Loader3.Loader (Loader.js:128)
    at new Loader (Loader.ts:79)
    at Application2.AppLoaderPlugin2.init (AppLoaderPlugin.ts:36)
    at Application.ts:112
    at Array.forEach (<anonymous>)
    at new Application (Application.ts:110)
    at (index):12
```
The final file is an HTML file with a test code. _(see beneath)_

### Environment

- **`pixi.js` version**: 6.0.2
- **Browser & Version**: Brave V1.23.71
- **OS & Version**: Windows 10 21H1 (19043.962)
- **Running Example**: Not really possible for now. [_This is what I try through._](https://github.com/Ayfri/PIXI-utils/blob/master/dist/index.html)

**Comment by SukantPal** [comment]
Please look at the tsconfig provided in the PixiJS 6 release notes, there are a few options that need to be enabled for it to work (and include mini-signals in your paths)

**Comment by Ayfri** [comment]
Still having the error, I'm using `gulp + esbuild` to compile everything from TypeScript into a single bundled js file.

**Comment by bigtimebuddy** [comment]
Can you please make a minimal reproduction (repo) which replicates this error? That would be very helpful.

**Comment by Ayfri** [comment]
It's happening when I launch in my browser the result of the `bundle` npm script from [here](https://github.com/Ayfri/PIXI-Extended).

**Comment by bigtimebuddy** [comment]
Debugging esbuild is out of scope for us. Beyond the tsconfig, which seems like already have setup correctly, I don't know what this is doing under the hood for the bundling and don't have time to dig in. If you can track down more specifically what the problem is and if Pixi is the source, happy to take a look at it. 

Unrelated, we should chat more about your project to extend Pixi. If you rolled some of your functionality into plugins that would be easier for people to consume. We've been trying to build an [ecosystem of packages](https://pixijs.io/customize/), might be helpful for more people than another bundle, but not sure what your longterm goal is for this project. Slack me if you want to chat more about how we might collaborate on this.
