### ISSUE TITLE
Feature request: support emojis with BitmapText and BitmapFont.from

### ISSUE THREAD

**Issue by mamaev37** [pixijs/pixijs#7631]
`
const style = new PIXI.TextStyle({
        fill: "white",
        fontFamily: "Ubuntu",
        fontSize: 50,
        strokeThickness: 5,
        align: "center",
    });

    const font = PIXI.BitmapFont.from("fontName", style, {
        resolution: 3,
        chars:['🔥🌏'],
    });
`
Does BitmapText support colored characters and how to connect them ?
Thank you for your attention! :)

**Comment by bigtimebuddy** [comment]
Text mostly supports this: https://jsfiddle.net/bigtimebuddy/sx3bapc2/

In order to support emojis on BitmapText, probably need to tweak how we resolve the list of characters. Here are the relevant pieces of code: 

https://github.com/pixijs/pixijs/blob/dev/packages/text-bitmap/src/utils/resolveCharacters.ts
https://github.com/pixijs/pixijs/blob/dev/packages/text-bitmap/src/BitmapFont.ts#L498-L519

Emojis are actually to characters that render as one, so things like `split('')` and `charCodeAt(0)` don't worry as intended. This this is definitely do-able. PR is welcome if someone would like to work on this feature.

**Comment by mamaev37** [comment]
bigtimebuddy, Thank you for the answer! and what should I do with this code fragment ? connect it separately ?

**Comment by eXponenta** [comment]
> bigtimebuddy, Thank you for the answer! and what should I do with this code fragment ? connect it separately ?

:) Refact it.
Accepting PRs means that functionality not supported yet and we wait hero which do it.

**Comment by mamaev37** [comment]
Понял! Спасибо!
