### ISSUE TITLE
SpritesheetLoader - (multi-pack) metadata used only for first image

### ISSUE THREAD

**Issue by Gawlas** [pixijs/pixijs#7714]
Hi,

I think I've found a bug, the problem occurs when we are loading sprite sheets that use the multi-pack feature and we provide "metadata" in loader options.

The problem is that "metadata" is used only when loading the first sprite sheet, it is not passed to rest spritesheets, so for example when we are specifying baseTexture options (imageMetadata), those options are used only in first texture.

In my opinion, "metadata" should be shared across all sprite sheets in multi-pack.

### Expected Behavior
"metadata" should be passed to rest sprite sheets.

### Current Behavior
"metadata" is not passed to rest sprite sheets.

### Possible Solution
pass metadata when adding rest multi-pack sprite sheets to the loader.

https://github.com/pixijs/pixijs/blob/dev/packages/spritesheet/src/SpritesheetLoader.ts (line 80)

```
const options = {
    crossOrigin: resource.crossOrigin,
    loadType: LoaderResource.LOAD_TYPE.XHR,
    xhrType: LoaderResource.XHR_RESPONSE_TYPE.JSON,
    parentResource: resource,
    metadata: resource.metadata
};
```

### Steps to Reproduce
https://codesandbox.io/s/pixi-spritesheetloader-metadata-rul1b

### Environment
- **`pixi.js` version**: 6.1.2

**Comment by ivanpopelyshev** [comment]
Grats! Make a PR?

**Comment by miltoncandelero** [comment]
I did all of this implementation without a paid licence of texture packer so my implementation might be slightly barebones 😅 

However... don't the other spritesheets have their own metadata? Are we sure we want to overwrite the metadata of the parts with the one from the first loaded?

IIRC multi-pack spritesheets are designed to point to each others what would mean that the metadata is meant to be on all files since you can download any of the multi parts and they will be linked. 🤔

**Comment by Gawlas** [comment]
I meant metadata passed in the loader options, not metadata inside sprite sheet (json file)

`loader.add("spritesheet.json", {metadata: {key: value}})`

**Comment by Gawlas** [comment]
@ivanpopelyshev 
I'll create PR tomorrow after add some tests

**Comment by Gawlas** [comment]
PR created: https://github.com/pixijs/pixijs/pull/7745
