### ISSUE TITLE
WebGL 1 is selected even though WebGL 2 is available

### ISSUE THREAD

**Issue by jnsmalm** [pixijs/pixijs#7835]
### Expected Behavior
That WebGL 2 is selected when available

### Current Behavior
WebGL 1 is sometimes selected even though WebGL 2 is available, happens on iPhone 12 with iOS 15. Using `PIXI.settings.PREFER_ENV = PIXI.ENV.WEBGL2` works so it should be selected by default.

### Steps to Reproduce
Create a application on iOS 15, check console for WebGL version.

### Environment
pixi.js v5.3.0 and v.6.1.3
Safari iOS 15

**Comment by bigtimebuddy** [comment]
It think that default behavior is expected:

https://github.com/pixijs/pixijs/blob/170e890aad69828c394417cafbb3c0a0d928e8d3/packages/core/src/settings.ts#L21

**Comment by themoonrat** [comment]
For https://github.com/pixijs/pixijs/blob/dev/packages/settings/src/utils/maxRecommendedTextures.ts a while back I made it so that by default it'd use as many as it could detect for mobile, unless we detected old version of Android or iOS. 
Could try a similar strategy here, and disable WebGL for iOS 14 and under, and Android 10 and under.... but iPad OS not revealing which version they are is a pain, and so iPads on older iOS devices might then get WebGL 2 and become unstable.....

Therefore imo it's safer to keep things as they are...

**Comment by EneaEntertainment** [comment]
ua string on iPad returns version for me

`Mozilla/5.0 (iPad; CPU OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/604.1`

or try detecting it directly on your device via this link [https://os.enea.sk](url)

**Comment by themoonrat** [comment]
You have your browser in mobile mode, but by default iPads report themselves as a Mac. They did for 13 and 14 at least, and it's these older versions we'd want to detect and rule out of WebGL 2

**Comment by EneaEntertainment** [comment]
indeed.. but when requesting desktop site doesnt version/15.0 still pointing to version with webgl2 support?

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15`
