### ISSUE TITLE
Huge performance drop when hardware acceleration is off in latest Google Chrome version, using webGL

### ISSUE THREAD

**Issue by CroutonUndercover** [pixijs/pixijs#7863]
### Expected Behavior
There should not be such a performance drop.

### Current Behavior

FPS drops to around 5-10 on different machines, CPU usage increases up to 90%.

https://github.com/pixijs/pixijs/blob/dev/packages/utils/src/browser/isWebGLSupported.ts
 On Google Chrome Version 91.0.4472.0 (Developer Build) (64-bit) HA off, my projects,  `isWebGLSupported()`  identified that webGL was not supported and it chose canvas rendering fallback, resulting in normal FPS where canvas fallback is possible. In https://pixijs.io/examples/#/demos-advanced/slots.js it seems there is no canvas fallback and webGL is used, resulting in abnormal CPU usage.
 
On Google Chrome Version 94.0.4606.81 (Official Build) (64-bit) HA off, my projects,  `isWebGLSupported()`  identified that webGL was supported and it choses webGL rendering, resulting in huge FPS drop, and increase of CPU usage by chrome up to 90% on lower end devices.

This behavior(mainly increased CPU usage) can be observed in https://pixijs.io/examples/#/demos-advanced/slots.js, with HA off on Chrome, other examples seem to work fine. 
There were no issues(CPU usage, FPS drop) with HA on, in any of the tests.

The issue seems to be difference between the way `isWebGLSupported()` behaves in older and latest versions of Chrome, possibly because of Chrome/SwiftShader changes recently. Currently if canvas fallback is provided during HA off, webGL is still preferred, even if it leads to performance drop.

A workaround is to detect if SwiftShader exist and choose canvas rendering if it does. Current way I found of doing that is to add this check in `isWebGLSupported()` :
```          
if(gl.getParameter(gl.getExtension('WEBGL_debug_renderer_info').UNMASKED_RENDERER_WEBGL).indexOf('SwiftShader') > -1){
```
The idea is that in Chrome, if SwiftShader is found, that would mean that hardware GPU is not used, and canvas fallback if necessary can be used. I realize that potentially it could be desired that webGL is used in cases where SwiftShader is detected, so a possible change would be to add ways to configure behavior in those cases. Although for me it seems, judging by the demo example performance with HA off, that at least on Chrome, canvas fallback should be the norm, unless it is found out what causes FPS drop/CPU usage increase, with HA off/webGL rendering.

### Tests on PIXI projects

PC: 5600x Ryzen, NVidia 3070, 16 RAM, Win 11
         Google Chrome Version 94.0.4606.81 (Official Build) (64-bit): **HA off - 17fps CPU usage 70%**, HA off(workaround)-  140fps
laptop:  Intel core i7-8550U 4 core, AMD Radeon r7 m440, 12 RAM, Win 10
        Google Chrome Version 94.0.4606.81 (Official Build) (64-bit): **HWA off- 5fps CPU usage(chrome) 90%**, HWA off(workaround)- 55fps, HWA on- 60fps,
        Google Chrome Version 91.0.4472.0 (Developer Build) (64-bit): HWA on/off/off with fix-  55 fps, CPU usage normal 
        
### Environment

- **`pixi.js` version**: 5.3.3
- **Browser & Version**: _Google Chrome Version 94.0.4606.81 (Official Build) (64-bit)
- **OS & Version**: Windows 10, Windows 11
- **Running Example**: https://pixijs.io/examples/#/demos-advanced/slots.js

**Comment by CroutonUndercover** [comment]
https://github.com/CroutonUndercover/pixi-demo  testing the workaround for the Slots example https://pixijs.io/examples/#/demos-advanced/slots.js, with HWA off, forcing canvas increases FPS from 30 to 70, CPU usage reduced from 80% to standard.

Console warnings with webGL/HWA off
![warnings](https://user-images.githubusercontent.com/11993789/137001233-546fbd9e-1b10-4d00-974d-67eba0060c0f.png)

**Comment by ivanpopelyshev** [comment]
Cards example is one of our best-selling :)

As an author of this example, I can tell you that BlurFilter there is made as an example. For performance on slow devices you have to do outlines in photoshop (its just one extra texture), and add a sprite instead. 5 blurfilters in a place where they are not needed at all , each blurfilter is a multipass - that's at least 20 operations with framebuffers. When fillrate is an issue (swiftshader, old integrated video) that is something that has to be taken down first. I'm sorry that we dont specify it with big letters across all the docs about filters.

As for swiftshader, I can tell you things that might affect it , and the only things we can actually affect from our side:

**Context Creationg Parameters.**

turn off antialias, if you turned it on for some reason
transparent:true transparent:false can also affect it

======

Alternatively, you can just use canvas2d. But wait! pixi-projection cant do perspecitve effects with it! 

There's actual solution: newest version of chrome (not sure about other browsers) gives ability to use 4x4 matrices in canvas2d! You just have to add a canvas renderer for projection.. how exactly? By posting and issue about it. Extra bounty can speed up things.

Why it wasnt done before? Because 1. no one needed it. 2. i didnt have time to look at it yet.  so, do you really really really need it?

**Comment by afarber** [comment]
Some users in my simple (no filters, just rectangles and text) word game report performance issues in latest Google Chrome and Yandex browsers too.

I am using 6.2.0 and explicitly `renderer: new PIXI.CanvasRenderer(),`
