### ISSUE TITLE
Graphics produces incorrect geometry for rounded rectangles

### ISSUE THREAD

**Issue by dev7355608** [pixijs/pixijs#7872]
`RoundedRectangle` is defined by circles (that's what the `contains` method tells us), but the graphics geometry builder uses quadratic bezier curves. Those two don't match. See example: green is the bezier rounded rectangle underneath the circle rounded rectangle in red.

### Environment

- **`pixi.js` version**:  6.1.3
- **Running Example**: https://www.pixiplayground.com/#/edit/UyCPdRdDHSCs8SueL9dki

**Comment by bigtimebuddy** [comment]
Correct, relevant code here: 
https://github.com/pixijs/pixijs/blob/bb47818dfa2c388f8adb6dbb3a8f32fdfb1e72a0/packages/graphics/src/utils/buildRoundedRectangle.ts#L97-L140

Open to using circles for the corner radius instead.

**Comment by ivanpopelyshev** [comment]
Yes, that's an inconsistency, we use parabolas for rounded rectangles, not circles/ellipses.  At the same time, browsers and adobe flash use regular circles/ellipses.

However we cant just change current code because that's a breaking change. Maybe make different modes and then switch default in next major version?
