### ISSUE TITLE
Using Pixi.js to draw large number of Polygons(over 10k) with interactive=true.

### ISSUE THREAD

**Issue by kohillyang** [pixijs/pixijs#7934]
I need to draw over 10k polygons and show something if the mouse is over one polygon. Since each polygon has its own hitArea, drawing them in one drawCall seems to be impossible. However, if I just create 10k Mesh for them then the framerate dropped to 1fps. Does this mean that the only way to achieve the goal is to pack them in one PIXI.mesh, and implement a picking algorithm by myself? It seems that such an algorithm needs lots of work. I have to assign a unique label for each polygon and render them to an offline buffer.

### Environment

- **`pixi.js` version**: 6.1.3_
- **Browser & Version**:  Chrome 93_
- **OS & Version**: windows10

**Comment by kjarrio** [comment]
Can you create a minimal reproduction on JSFiddle / CodePen / PixiJS Playground / Replit / etc?

**Comment by ivanpopelyshev** [comment]
You are asking about two big problems at the same time.

## "10k bunnies" problem.

**Low-level:**

single PIXI.Mesh - static or dynamic, if you know exactly how to calculate your vertices.

many PIXI.Graphics /PIXI.Mesh, maybe with same geometry, Batching can do it fast, but it requires CPU resources.

**High-level:**

whatver you can imagine to separate your content to several parts and process each one with low-level. Its your side, you have to write it, PixiJS doesnt have that, otherwise you could be sapped to neural network.

##  Interaction

Its dfferent. PixiJS interaction is basic, look in https://github.com/pixijs/pixijs/blob/dev/packages/interaction/src/TreeSearch.ts

you can make your own, optimized search and do `renderer.interaction.search = mySearch` . 

Also for low-level elemvents you use - you can add custom `containsPoint`.

The reason why pixijs doesnt have anything fast by default, is because **it depends on user stag**e. So far no one provided us good algo that doesnt make code unreadable and suits all the cases.

## Summary

Of course its possible to make several algorithms both for high/low level and for interaction, and give them to users. But, so far, no one made good enough plugin for it. Everyone are using their stuff in their games, and not sharing it. If you want to affect it - please share your code when its ready, document it, make sure its up-to-date with latest pixi release , e.t.c.

**Comment by kohillyang** [comment]
Thanks for your reply, I found picking in pixi.js is fast enough in this case, and the reason why the framerate dropped seems to be a little strange. So I close this issue and close another one to talk about that.

**Comment by ivanpopelyshev** [comment]
Its more discussion than the issue. Please post new one in discussions.
