### ISSUE TITLE
Best practice for rendering max 200K potentials text

### ISSUE THREAD

**Issue by zip87** [pixijs/pixijs#7939]
Hi,

hi, 
I’m building a gantt chart which can contain over 200k objects.  I have not encountered problems with the objects, but with the text of each of them. How can you proceed in these cases?

Many thanks

**Comment by ivanpopelyshev** [comment]
BitmapText only. if you need scale  - use SDF or MSDF.

**Comment by ivanpopelyshev** [comment]
also, 200k should be culled. really. 

Read my post here: https://github.com/pixijs/pixijs/issues/7934#issuecomment-955658630

i posted it like 50 times already. People dont get it - PixiJS provides **low-level** part of solution. If you ask to render 200k elements withotu a problem - you have to write good **high-level** too! Otherwise , you as a coder can be easily replaced by neural network.
