### ISSUE TITLE
Can't run "npm i" on PixiJS with npm 8

### ISSUE THREAD

**Issue by ShukantPal** [pixijs/pixijs#7964]
Is this intentional?

https://github.com/pixijs/pixijs/blob/f1c18ad5b2aca53791d8330d17bf45b718106fe6/package.json#L51

**Comment by domis86** [comment]
@ShukantPal it seems it was introduced by @bigtimebuddy in https://github.com/pixijs/pixijs/pull/7929 - there is something about "npm bug" in description there

**Comment by bigtimebuddy** [comment]
This is because npm >= 7.20.3 produces [an error](https://github.com/npm/cli/issues/3964) when attempting to do the version bump on the package-lock.json.

npm@8 should be fine for hosting and building, just not doing a release. I can add a check before doing a release to make sure npm is >=7 and < 7.20.3 so that we can support 8 more generally for the repo.
