### ISSUE TITLE
Font Baseline Bug

### ISSUE THREAD

**Issue by rizen** [pixijs/pixijs#8020]
### Expected Behavior

All letters from different fonts would line up along their baseline like they do in HTML.

<img width="276" alt="Screen Shot 2021-11-27 at 4 57 56 PM" src="https://user-images.githubusercontent.com/170009/143722700-d5ed950b-01c1-4e73-b291-b8cb3b989437.png">

### Current Behavior

Depending upon the font, the letters can be all over the place, even though they look great in HTML. Sometimes it gets so bad that it will cut off the bottom of the letter. 

<img width="370" alt="Screen Shot 2021-11-27 at 4 58 04 PM" src="https://user-images.githubusercontent.com/170009/143722698-d63d5691-d041-4575-97df-264ad669bb7e.png">

### Possible Solution

Not sure, or I would submit a patch.

### Steps to Reproduce

I've created a fiddle: https://jsfiddle.net/plainblackguy/dfcm6hjL/14/

### Environment

- **`pixi.js` version**: _6.2.0_
- **Browser & Version**: _Chrome 96.0.4664.55 and Safari 14.1.2, but probably all browsers_
- **OS & Version**: _e.g. Mac OS 11.6 and Windows 10_
- **Running Example**: https://jsfiddle.net/plainblackguy/dfcm6hjL/14/

**Comment by bigtimebuddy** [comment]
This is somewhat of a fundamental problem with how Text renders in Pixi. Since we don't have access to the font metrics directly (doing so would require a heavy third-party library), we rely on roughly [measuring the baseline](https://pixijs.download/dev/docs/PIXI.TextMetrics.html#BASELINE_SYMBOL) for each font. This can vary wildly from font to font, as you've discovered producing different results if you're trying to align different typefaces.

Text is in desperate need of an overhaul. Or an alternative that prioritizes layout and accuracy over style options (gradients, drop-shadows, etc). You're welcome to try this alternative https://github.com/pixijs/html-text which behaves a lot like Text and has a nearly identical API but has some significant caveats in the README.

**Comment by rizen** [comment]
Is HTML-Text the future, or is it more likely that something else is the future of text in Pixi?

**Comment by rizen** [comment]
Also, HTML-Text doesn't support custom fonts according to this: https://github.com/pixijs/html-text/issues/2

So that would be a deal breaker for me.

**Comment by eXponenta** [comment]
MSDF Fonts is main candidate for replace default pixi Text. 

As alternative you can use a Truetype fonts and draw a their shapes directly (can be replacement for line build method of Text class)
But require a TTF files and parser, and can't be used for system fonts, this is reason why it can't be used inside pixi core.

https://github.com/RazrFalcon/ttf-parser/tree/afb43be7ef8471ae75db1fe4f03cfc3f07d35519
