### ISSUE TITLE
Unexpected BitmapText text width calculation

### ISSUE THREAD

**Issue by ssavova** [pixijs/pixijs#8246]
BitmapText textWidth has different value for lines with same amount of symbols (monospace font). Actually, according to the documentation, it is stated that at the latest pixi version (6.3.0), this bug must be fixed and the textWidth for characters '11' must be the same as for '33'. 

However, if you observe the **example here**: https://www.pixiplayground.com/#/edit/kvfNbd8URsDHhYWeVp83V 
You can see that the **bug still persist** and there is discrepancy between "11" and "33" textWidth. This discrepancy leads to unexpected and undesired BitmapText "shake". 

**Environment**

**pixi.js version:** > 6.0.0
**Browser & Version:** Chrome/FF
**OS & Version:** Windows
**How does it work now (pixi 6.3.0):** https://www.pixiplayground.com/#/edit/kvfNbd8URsDHhYWeVp83V

**Comment by bigtimebuddy** [comment]
Arial is not a monospaced font, this should not work.

**Comment by ssavova** [comment]
Yes, it`s my fault to consider Arial as monospaced font, but the same example, using pixi ( v5.3.0) behave as expected - no difference between  "11" and "33" textWidth. Could you please explain to me the reason for this behaviour.

**Comment by bigtimebuddy** [comment]
The reason that this issue is happening is because older versions of Pixi did not consider kerning between letters for BitmapFont. This is actually really useful if you want to have a words like `ball` but with the `ll` to be closer together. This is achieved with measuring kernings between letters when the BitmapFont is created. It was introduced here: #6888 (v6.0.0)

If you want to ignore kernings, you can add this to your example:
```js
const { chars } = PIXI.BitmapFont.from(customFont.name, customFont.style, customFont.options);
Object.keys(chars).forEach((code) => (chars[code].kerning = {}));
```

BitmapFont _may_ benefit from having an option to skip kernings being generated. PR is welcome to add this to the BitmapFont.from options.

**Comment by GoodBoyDigital** [comment]
closing as we also have `skipKerning` in both v7 and v8 👍
