### ISSUE TITLE
Add background feature Application.

### ISSUE THREAD

**Issue by Ayfri** [pixijs/pixijs#8346]
Hello, I multiple time needed a background sprite for my games because I needed a texture and not a color. But every time I just create a sprite at start, put it in back with a very low z-index for future, resize it with `resize` event and leave it alone. And I always have the exact same code as it's just a background, so, it could be great to have a background functionality to Application class !
Or even Renderer, and it could accept a Sprite or just a texture so it's lightweight.

I think just a private property with getter+setter and an option in the ApplicationOptions should be enough, and the background will be resized to the renderer size when it changes.

As it is a very common thing to do, I think it could be a great feature :)

For even more advanced feature you could offer a parallax effect with other properties defining the size of the background, and if it is bigger than the renderer size, then a `speed` property will define the speed at which the background is moving, and maybe a `blockToRendererSize` property set to false would make the sprite not stopping when reaching a bound.
But that's just an optional idea more complex and especially hard to be highly configurable for everyone.

**Comment by bigtimebuddy** [comment]
You can easily do this with an Application plugin. One of the lesser know extendible APIs.

Here's a running example: https://jsfiddle.net/bigtimebuddy/v4qbwcfL/

I don't think this is a core feature, but if you want to make/publish a plugin from that example, go ahead. This starts to get more into convention territory which is why I say it's not a core feature. Managing the zIndex correctly can get kinda tricky.
