### ISSUE TITLE
Sprite scale worry

### ISSUE THREAD

**Issue by Elon-Yan** [pixijs/pixijs#8362]
When Sprite has set width or height, this scale is worry.
demo: https://jsfiddle.net/32eabc1h/1/ 
Sprite's width is 100px, when I set scale to 0.2.
I think Sprite's width is 20px, but not.

**Comment by Julien-Marcou** [comment]
This is because setting the width of the sprite to 100px does not actually change the width of the sprite, but changes its scale to make it look like it is 100px wide.

From the [documentation](https://pixijs.download/dev/docs/PIXI.Sprite.html#width):
`The width of the sprite, setting this will actually modify the scale to achieve the value set`

The sprite internally retains the size of the texture you give it.
Because your texture is 528px wide, setting the width of the sprite to 100px will scale your sprite to ~0.19, that's why when you ask for a scale of 0.2, it will sligthly increase its renderer width.

You can achieve what you want by wrapping your sprite in a `Container` and scaling the container instead (or just by setting the width of the sprite to 20px in the first time).

```js
const spriteTexture = Texture.from('https://i.postimg.cc/DwZ1Sq7h/avataaars.png');
const sprite = new Sprite(spriteTexture);
sprite.x = 100;
sprite.y = 100;
sprite.width = 100;
sprite.height = 100;

const spriteContainer = new Container();
spriteContainer.scale.x = 0.2;
spriteContainer.addChild(sprite);

app.stage.addChild(spriteContainer);
```
