### ISSUE TITLE
PIXI.Sprite memory leaking in Safari

### ISSUE THREAD

**Issue by MorookaKotaro** [pixijs/pixijs#8399]
### Expected Behavior
When a PIXI.Sprite is disabled, GC works correctly in Safari.

### Current Behavior
Seems GC doesn't work. The memory usage is increased as the Sprite is re-rendered.

![スクリーンショット 2022-06-13 14 33 28](https://user-images.githubusercontent.com/62707539/173287153-4c531321-3675-4eb4-8815-f873074f2e23.png)

### Environment

- **`pixi.js` version**: v5
- **Browser & Version**: Safari 15.5
- **OS & Version**: _e.g. Mac 11.6.6(Big Sur)
- **Running Example**: https://codesandbox.io/s/staging-architecture-tl7v0x?file=/src/index.ts

**Comment by miltoncandelero** [comment]
Have you tried calling `sprite.destroy()`? does that helps? 🤔

**Comment by bigtimebuddy** [comment]
Calling `PIXI.Sprite.from` every interval is the same thing as creating a `new PIXI.Sprite`. New objects in PIXI are not free and they do not get collected automatically by GC, even if the Textures used by the Sprite are cached. You need to call `destroy()` on each Sprite if you want to get rid of them (as @miltoncandelero said above).

So this is not a bug or memory leak, but very much intended to work this way.

It is best practice to reuse your Sprites or PIXI object and pool them (instead of continually create/destroy). In addition, make sure your textures are cached and preloaded as well. If you do this, memory will be flat.

**Comment by MorookaKotaro** [comment]
@miltoncandelero @bigtimebuddy 
I tried destroy method, then the memory looks good!
Although, it's still not the best way, creating / destroying repeatedly works well.

Thank you, both.

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/62707539/173496606-aa8890ef-d62e-40b7-a951-2117ad05b9a5.png">
