### ISSUE TITLE
Sub-folders ignored with new Asset loader

### ISSUE THREAD

**Issue by Dunnings** [pixijs/pixijs#8610]
Related to https://github.com/pixijs/pixijs/pull/8605

### Expected Behavior
In v6.5.1 assets loaded from a subfolder used the correct URL

#### Example 1:
Website URL:  **http://www.exampleurl.com/mypage/index.html?variable=test**
Asset Path: **img/logo.png**
Resolved URL: **http://www.exampleurl.com/mypage/img/logo.png**

#### Example 2:
Website URL:  **http://www.exampleurl.com/mypage/index.html?variable=test**
Asset Path: **/img/logo.png**
Resolved URL: **http://www.exampleurl.com/mypage/img/logo.png**

### Current Behavior
In v6.5.2 assets loaded from a subfolder are using the incorrect URL

#### Example 1:
Website URL:  **http://www.exampleurl.com/mypage/index.html?variable=test**
Asset Path: **img/logo.png**
Resolved URL: **http://www.exampleurl.com/mypage/index.html?variable=test/img/logo.png**

#### Example 2:
Website URL:  **http://www.exampleurl.com/mypage/index.html?variable=test**
Asset Path: **/img/logo.png**
Resolved URL: **http://www.exampleurl.com/img/logo.png**

### Possible Solution
You can add the subfolder to the asset path, but the subfolder may change depending on where the built files are hosted.

### Steps to Reproduce
Create a project with the above asset structure and use the above asset path.

### Environment
- **`pixi.js` version**:  6.2.2

**Comment by Zyie** [comment]
Hey, thanks for reporting this

The current behaviour for example 1 is correct and matches the behaviour of the old pixi loader

```
Example 1:
Website URL: http://www.exampleurl.com/mypage/index.html?variable=test
Asset Path: /img/logo.png
Resolved URL: http://www.exampleurl.com/img/logo.png
```

The `6.5.1` version of the asset loader didn't take into account `root-relative` pathing. In order to get the same behaviour as before you would need to add `./` to the start of the asset path e.g. `./img/logo.png`, or omit the `/` altogether e.g. `img/logo.png`

As for the second example, yes this is a bug. It seems that the `basePath` doesn't remove url params before calculating the new path. Will look into fixing this!

**Comment by Dunnings** [comment]
Thanks for checking and replying @Zyie. There was a mistake in the current behaviour examples above. Have fixed that now.

**Comment by Zyie** [comment]
Hey @Dunnings a PR is up to fix this. Let me know if you have any issues with it
