### ISSUE TITLE
Needs a param as loopCount in AnimatedSprite.onloop() method.

### ISSUE THREAD

**Issue by aswind** [pixijs/pixijs#8752]
### Expected Behavior
When onloop methed of AnimatedSprite is called, we need to know how many loops are completed in the callback.
### Current Behavior
When onloop methed of AnimatedSprite is called, we don,t know how many loops are completed in the callback.
### Possible Solution
It is better to have a parameter as loopCounts in the callback: AnimatedSprite.onloop(loopCount).
### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by DashShantanu** [comment]
Hello! I want to contribute on this issue. Could you assign this to me?

**Comment by SuperSodaSea** [comment]
> Hello! I want to contribute on this issue. Could you assign this to me?

@DashShantanu Sure!

**Comment by garveyz2** [comment]
Hi, is this issue still open? If so, I would like to work on it.

**Comment by SuperSodaSea** [comment]
> Hi, is this issue still open? If so, I would like to work on it.

@garveyz2 PR is welcomed :)

**Comment by bigtimebuddy** [comment]
Thanks you @aswind for the suggestion. After consideration, we decide to not accept this feature because of low-impact of adding it as well as having to be too opinionated about some of the details.

Alternatively, I would suggest you track this value yourself, for instance:

```js
const anim = new SpriteAnimation();
let loops = 0;
anim.onLoop = () => {
  ++loops;
};
```

Please continue to make more feature suggests. Thank you!
