### ISSUE TITLE
When the width and height of texture are not integer power of 2, the result of BitmapFont.from looks worse

### ISSUE THREAD

**Issue by Redgeioz** [pixijs/pixijs#8775]
### Expected Behavior
When given texture sizes are similar, their effects should be similar

### Current Behavior
When the width and height of texture are not integer power of 2, the effects of generated bitmap font look worse after changing scale.
![image](https://user-images.githubusercontent.com/52198272/197407532-b6132e13-4e62-4fbd-8dc9-5853bbf5c5f4.png)
1. Texture size: 511x511
2. Texture size: 512x512
3. Texture size: 513x513

### Steps to Reproduce
https://www.pixiplayground.com/#/edit/4-KX0SsB4-Cv5UYesU4dS

### Environment

- **`pixi.js` version**: _above 5.3.0_
- **Browser & Version**: _Chrome 106.0.5249.119 & Edge 106.0.1370.47 & Firefox 106.0_
- **OS & Version**: _Windows 10_

**Comment by SuperSodaSea** [comment]
Seems that adding `PIXI.settings.MIPMAP_TEXTURES = PIXI.MIPMAP_MODES.ON` at the begining of the code can solve this problem. `MIPMAP_TEXTURES` is `POW2` by default, so if the texture is NPOT , they will look worse.

https://github.com/pixijs/pixijs/blob/3ba43e50030641e2cb028c7c265e80ce0fdf6fff/packages/settings/src/settings.ts#L95

I think it is OK to change the default value of `MIPMAP_TEXTURES` to `ON`, since PixiJS can automatically disable mipmap for NPOT textures on WebGL 1.

https://github.com/pixijs/pixijs/blob/3ba43e50030641e2cb028c7c265e80ce0fdf6fff/packages/core/src/textures/TextureSystem.ts#L415-L418

**Comment by Redgeioz** [comment]
> Seems that adding `PIXI.settings.MIPMAP_TEXTURES = PIXI.MIPMAP_MODES.ON` at the begining of the code can solve this problem. `MIPMAP_TEXTURES` is `POW2` by default, so if the texture is NPOT , they will look worse.
> 
> https://github.com/pixijs/pixijs/blob/3ba43e50030641e2cb028c7c265e80ce0fdf6fff/packages/settings/src/settings.ts#L95
> 
> I think it is OK to change the default value of `MIPMAP_TEXTURES` to `ON`, since PixiJS can automatically disable mipmap for NPOT textures on WebGL 1.
> 
> https://github.com/pixijs/pixijs/blob/3ba43e50030641e2cb028c7c265e80ce0fdf6fff/packages/core/src/textures/TextureSystem.ts#L415-L418

Yes, it even helps me solve another problem I was struggling with.

**Comment by SuperSodaSea** [comment]
I will make a PR for this later.

**Comment by SuperSodaSea** [comment]
After a discussion it seems that changing the default value can cause significant extra graphics memory usage / bandwidth usage, and affect many existing code. Also using Power-Of-Two textures instead of the Non-Power-Of-Two textures is always a good idea. So I think it is better NOT to change the default value of `setting.MIPMAP_TEXTURES`, and leave the choice to users if you really need this.
