### ISSUE TITLE
PIXI.Spritesheet Throws Error with v6.5.8

### ISSUE THREAD

**Issue by talhaozdemir** [pixijs/pixijs#8778]
Previously below code working with no problem but today after I update pixi version to the latest I got following error:
```
    Assets.add(key, imageFile);
    const asset = await Assets.load(key);

    if (atlasData.textures) {
      atlasData.frames = atlasData.textures[0].frames;
      atlasData.textures = null;
    }

    const sheet = new Spritesheet(
      asset.baseTexture,
      atlasData
    );
```

![image](https://user-images.githubusercontent.com/37840852/197448207-2675446b-6672-4ae7-be45-1e70dd7c728c.png)

![image](https://user-images.githubusercontent.com/37840852/197448241-d8dbb70d-fb06-430a-b939-e48418c5e1c2.png)

`asset.baseTexture` returns Texture, it is not null or undefined.

- **`pixi.js-legacy` version**: 6.5.8

**Comment by bigtimebuddy** [comment]
Spritesheets still work: https://pixijs.io/examples/?v=v6.5.8#/sprite/animatedsprite-jet.js

I know we've been through this, but you followed [this](https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS) when upgrading?

**Comment by talhaozdemir** [comment]
No, because I have to load spritesheet image as base64 to pack app in a single HTML file, so I load json and png seperately. In the jsfiddle example, loader loads asset with json.

**Comment by talhaozdemir** [comment]
```
// I put spritesheet data in an object
              {
                type: "atlas",
                imageFile: require('../assets/ui/fx/revoltfx-spritesheet.png'),
                atlasData: require('../assets/ui/fx/revoltfx-spritesheet.json'),
                key: "revoltfx-spritesheet"
            },
  
  // then, I seperate spritesheet frames by using Spritesheet parse method.
  async loadAtlas(key, imageFile, atlasData, callback) {
    Assets.add(key, imageFile);
    const asset = await Assets.load(key);

    if (atlasData.textures) {
      atlasData.frames = atlasData.textures[0].frames;
      atlasData.textures = null;
    }

    const sheet = new Spritesheet(
      asset.baseTexture,
      atlasData
    );

    function parse() {
      return new Promise(function (resolve, reject) {

        const resources = PIXI.Loader.shared.resources;
        resources[key] = {};
        resources[key].animations = sheet.animations;
        resources[key].data = sheet.data;
        resources[key].frameTextures = sheet.textures;
        resources[key]._frameKeys = sheet._frameKeys;
        resources[key]._frames = sheet._frames;
        resources[key].resolution = sheet.resolution;

        sheet.parse();
        resolve();
      });
    }
    parse().then(() => {
      callback();
    });
  }
  
  // Lastly, I use spritesheet animation like that:
          /** @type {AnimatedSprite} */
        const obj = new AnimatedSprite(
            Loader.shared.resources['atlas'].animations['confetti']
        );
        scene.addChild(obj);
        obj.play();
        obj.animationSpeed = 0.3;
```

**Comment by talhaozdemir** [comment]
By the way, if I can load png asset as base64 in the json file, I can use it like in your jsfiddle example.

**Comment by bigtimebuddy** [comment]
Thanks for the explanation, however, this is unfortunately still insufficient. Having a minimal reproduction (runnable code or standalone repo) will tell us whether this is a problem with your project, your code or pixi's. These examples don't make that any clearer because it is omitting important details. The broadest possible view with the minimal amount of code is the easiest way to help triage your issue.

If I had to guess this is a problem with your dependencies/upgrading not with pixi's code. We have no recent changes in 6.5.8 to Assets or Spritesheet, however, what does seems obvious to me is that the Spritesheet's constructor is doing `instanceof` checks. If there are multiple instances of `@pixi/core` in your code (say one imported by `@pixi/spritesheets` and one imported by `@pixi/assets`), this would mean both `instanceof` statements would fail and baseTexture would be undefined.

Verify in your package-lock.json/yarn.lock file that you only have _one_ `@pixi/core` version and that `@pixi/assets` matches the same version as `pixi.js-legacy`.

**Comment by talhaozdemir** [comment]
Because I am using webpack, I cannot share reproduction. But I will try it on jsfiddle and I will check package-lock.json for duplication and update here tomorrow.

**Comment by talhaozdemir** [comment]
You were right @bigtimebuddy I deleted `node_modules` folder and` package-lock.json` file and then run `npm install`. Now it is working. Thanks and I'm sorry for wasting your time.

**Comment by bigtimebuddy** [comment]
No worries. We are all learning. Thanks for confirming.
