### ISSUE TITLE
No way to change renderer resolution in 7.0?

### ISSUE THREAD

**Issue by davidye** [pixijs/pixijs#8792]
Previously resolution could be set after initialization, but in 7.0 that doesn't appear to be possible anymore: https://github.com/pixijs/pixijs/blob/4cbadba3e46c4987f505e76a7f4e844d95a120cc/packages/core/src/Renderer.ts#L481

A browser's window.devicePixelRatio can dynamically change due to page zoom so it's necessary to update resolution between renders without having to reinitialize everything.

### Environment

- **`pixi.js` version**: 7.0.0

**Comment by bigtimebuddy** [comment]
This came up recently here: https://github.com/pixijs/pixijs/discussions/8739#discussioncomment-3970714

Setting `renderer._view.resolution` should do the same thing. We made this read-only for a reason because we had low confidence that it actually worked for all elements. This needs some more testing/investigation to make sure it works as expected.
