### ISSUE TITLE
Pixi 7 errors: Argument of type '...' is not assignable to parameter of type 'DisplayObject'.

### ISSUE THREAD

**Issue by anisabboud** [pixijs/pixijs#8810]
How to handle these new errors? Didn't find info in the [v7 migration guide](https://github.com/pixijs/pixijs/wiki/v7-Migration-Guide).

- `Argument of type 'Container<DisplayObject>' is not assignable to parameter of type 'DisplayObject'.`
  example line: app.stage.addChild(mainStage);
- `Argument of type 'ParticleContainer' is not assignable to parameter of type 'DisplayObject'.`
  example line: `mainStage.addChild(particleContainer)`
- `Argument of type 'Graphics' is not assignable to parameter of type 'DisplayObject'.`
  example line: `mainStage.addChild(roundedCornerMask)`
- `Argument of type 'Text' is not assignable to parameter of type 'DisplayObject'.`
  example line: `mainStage.addChild(text)`
  example line: `sprite.addChildAt(text, 0)`
  example line: `mainStage.removeChild(text)`
- `Argument of type 'Text' is not assignable to parameter of type 'DisplayObject | DisplayObject[]'.`
  example line: `ease.add(text, ...)`

**Comment by bigtimebuddy** [comment]
Please provide reproduction, thanks!

**Comment by anisabboud** [comment]
There is no reproduction here. These are errors in my code resulting from the upgrade to v7.
In multiple locations I'm getting errors that something `is not assignable to parameter of type 'DisplayObject'`
Can you explain what changed around 'DisplayObject' so that we can understand how to update the code accordingly?

**Comment by ASDFGerte** [comment]
You are most likely using yarn pnp (or any package manager that isn't loose about dependencies), and this is the same as https://github.com/pixijs/pixijs/issues/8798

**Comment by bigtimebuddy** [comment]
What I was asking for a reproduction is could you provide a minimal reproduction on GitHub that reproduces these type errors (outside your project). There are important factors when we are trying to diagnose these issues about the development environment (dependencies, ts setup, package-manager, etc) that are completely missed here by these generic typing errors.

Ultimately, I think this is the same root cause as #8809, two versions (v6 and v7) of PixiJS being installed fighting over types. You can confirm this in your lock file if you see multiple versions of `@pixi/core`, `@pixi/display` etc.

**Comment by anisabboud** [comment]
Now that `@pixi/sound` and `@pixi/particle-emitter` support pixi.js 7, I retried the process.

I removed `@pixi/assets` from package.json as you suggested (since it's no longer needed separately in v7), updated all pixi packages to latest, removed `package-lock.json` and `node_modules`, and ran a fresh `npm install`.

That resolved the errors, so your guess is correct - there were two versions of PixiJS (v6 and v7) installed alongside each other due to the dependencies, causing these errors. Thanks for the tip.
