### ISSUE TITLE
Lines break batching

### ISSUE THREAD

**Issue by BarberDuckyFazi** [pixijs/pixijs#8894]
### Expected Behavior
Batching should not break when drawing lines successively, without using masks or filters.
 
### Current Behavior
Batching breaks when drawing lines successively, all while not using masks or filters.

### Possible Solution
/

### Steps to Reproduce
Code: https://www.pixiplayground.com/#/edit/Ajwf5UnUgNQST1-zd7LUx

Batch breaking was observed using the Spector.js extension: https://chrome.google.com/webstore/detail/spectorjs/denbgaamihkadbghdceggmchnflmhpmk?hl=en

Please consider the following video:
https://user-images.githubusercontent.com/93976151/203809647-a90ed870-e865-4384-9767-d3cb10afe64b.mp4

### Environment

- **`pixi.js` version**: latest in playground
- **Browser & Version**: latest stable chrome
- **OS & Version**: _e.g. Ubuntu 22.04_
- **Running Example**: https://www.pixiplayground.com/#/edit/Ajwf5UnUgNQST1-zd7LUx

**Comment by bigtimebuddy** [comment]
Good question! This is a good opportunity to understand how Graphics batch.

In PixiJS, Graphics are difficult to batch because something can be very simple, like a rectangle, or complicated like an illustration. The more complex something is the more it can slow down the batching path, so  PixiJS defines what is batch-able based on the the number of points after triangulating the geometry. 

https://github.com/pixijs/pixijs/blob/936b210ca553a804791b1704da13dbffbcc06550/packages/graphics/src/GraphicsGeometry.ts#L47

In your example, you have 4 lines. Each line, after triangulating, is 200 points (i.e., 400 x/y values). I updated your example:
https://www.pixiplayground.com/#/edit/Ajwf5UnUgNQST1-zd7LUx so you can see that this will not batch.

Fortunately, there are numerous ways to fix batching!

* Adjust the `GraphicsGeometry.BATCHABLE_SIZE`. While this is an arbitrary amount, I wouldn't go too crazy fiddling with this, probably not the best idea.
* Since PixiJS draw curves (e.g., the rounded line ends) adaptively, you can render your lines small and scale them up. [Here](https://www.pixiplayground.com/#/edit/oxewcanlbgEsmygaHvfms) is an example of that.
* Render your Graphics using a RenderTexture (i.e., converts into a sprite)

Also, I wrote an article about this subject here:
https://medium.com/@bigtimebuddy/rendering-fast-graphics-with-pixijs-6f547895c08c
