### ISSUE TITLE
Graphics beginTextureFill weird size behavior

### ISSUE THREAD

**Issue by Skinify** [pixijs/pixijs#8905]
### Problem
The graphics object gives a wrong size when used the .beginTextureFill method, but it works using the .beginFill
### Expected Behavior
Output the right graphics size
### Current Behavior
Outputting the graphic size (height, width) as zero

### Code Sample (Weird behavior)
const backgroundTexture1 = require("any_image.png");

var _graphic = new PIXI.Graphics()
  .beginTextureFill({
    texture: PIXI.Texture.from(backgroundTexture1),
    color: 0x2f2217,
  })
  .drawRoundedRect(0, 0, 100, 100, 4)
  .endFill();

this.addChild(_graphic);
console.log("Graphic height " + _graphic.height);
// Output: "Graphic height 0"

- **`pixi.js` version**:  7.0.4

**Comment by bigtimebuddy** [comment]
Make sure the texture is preloaded.

**Without preloading:**
https://pixiplayground.com/#/edit/yx4uby0aeC6jCfiilFHi4

**With preloading:**
https://pixiplayground.com/#/edit/VRBRlEZskJt9fzP-1aNBU

The reason is that `Texture.from` is asynchronous, lazy-loading the texture in the background. From the time between when you create `new Graphics` to the `console.log` the Texture is invalid. Once is becomes valid, the Graphic is a valid width/height.

**Comment by Skinify** [comment]
@bigtimebuddy Thxx
