### ISSUE TITLE
Class constructor Sprite cannot be invoked without 'new'

### ISSUE THREAD

**Issue by twincle** [pixijs/pixijs#8923]
```
import {
  Point,
  Sprite,
  Texture,
} from 'pixi.js';

import bunny from '../bunny.png';

export class SpriteBunny extends Sprite {
  
  public constructor () {
    super(Texture.from(bunny));

    this.pivot = new Point(-10, -10);
    this.x = 100;
  }

}
```

### Current Behavior
Uncaught TypeError: Class constructor Sprite cannot be invoked without 'new'
    at new SpriteBunny (base.ts:12:5)

### Environment

- **`pixi.js` version**: _7.0.4_
- **other**: _webpack  typescript_
- **Browser & Version**: _edge 107.0.1418.62 (x64)_
- **OS & Version**: _Windows 11_

**Comment by bigtimebuddy** [comment]
Probably because of [this](https://bobbyhadz.com/blog/typescript-class-constructor-cannot-be-invoked-without-new#:~:text=The%20%22Class%20constructor%20cannot%20be,new%20operator%20when%20instantiating%20classes.)?

Can you make sure that your tsconfig.json target is at least es6?

If that doesn't work, could you please create a repo that minimally reproduces the issue?

**Comment by twincle** [comment]
> Probably because of [this](https://bobbyhadz.com/blog/typescript-class-constructor-cannot-be-invoked-without-new#:~:text=The%20%22Class%20constructor%20cannot%20be,new%20operator%20when%20instantiating%20classes.)?
> 
> Can you make sure that your tsconfig.json target is at least es6?
> 
> If that doesn't work, could you please create a repo that minimally reproduces the issue?

thank you very much. your answer is correct. thank you
