### ISSUE TITLE
Bug: Graphics.lineTextureStyle does not fill texture properly (v6.5.0)

### ISSUE THREAD

**Issue by redbeardmickey** [pixijs/pixijs#9013]
### Current Behavior

Drawing lines with lineTextureStyle does not seem to have the correct texture/pattern.

### Expected Behavior

Drawing lines with lineTextureFill should have the correct texture/pattern.

### Steps to Reproduce

Working fine until v6.4.2:
https://codesandbox.io/s/linetexturestyle-ezl397

Broken on v6.5.0:
https://codesandbox.io/s/linetexturestyle-forked-6eivg7

### Environment

- **`pixi.js` version**: *6.5.0*
- **Browser & Version**: *Edge 108.0.1462.54*
- **OS & Version**: *macOS Ventura*
- **Running Example**:
  - Before: *https://codesandbox.io/s/linetexturestyle-ezl397*
  - After: *https://codesandbox.io/s/linetexturestyle-forked-6eivg7*

### Additional Information

If there are better ways to achieve the effect, please advise 😄 .

**Comment by bigtimebuddy** [comment]
The reason this is happening is because in 6.5.0+ we changed how Graphics bounds are measured. In general, this was to be more accurate with strokes when figuring out bounds, but it had some consequences. No longer are shapes with 0 alpha considered to be part of the bounds of the Graphics object. In your case, you were creating an alpha at the end of your dash sequence which wasn't getting picked up when converting to a Texture.

Here's a hack where you can see the difference by drawing a fill over the whole shape:
https://codesandbox.io/s/linetexturestyle-forked-8hq93r?file=/src/index.js

There are a number of ways you can address this:

* Don't start or end your dashed texture with an alpha
* Resize the texture
* Use the alpha hack above

**Comment by redbeardmickey** [comment]
Thanks @bigtimebuddy for your response and solutions!
