### ISSUE TITLE
Bug: HTMLText does not take into account pixi app resolution

### ISSUE THREAD

**Issue by RhapsodY-69** [pixijs/pixijs#9213]
Hello!

### Current Behavior

If you set pixi.js app resolution to anything higher than 1, text sprite becomes smaller

### Expected Behavior

Works fine with any pixi.js resolution

### Steps to Reproduce

Here is example where pixi regular text and HtmlText with fontSizes 24px differ by 2 times in size, where 2 is pixi.js app resolution
https://jsfiddle.net/Rhapsody6969/d49h51bg/15/

### Environment

- **`pixi.js` version**: *7.0.2*
- **Browser**: *Chrome*
- **OS**: *MacOS*
- **Running Example**: https://jsfiddle.net/Rhapsody6969/d49h51bg/15/

### Possible Solution

Use text sprite scale property set to same resolution number, but there are other problems with it

**Comment by bigtimebuddy** [comment]
I see the problem. You're using an absolute size inline. The way resolution is applied to HTMLText is by multiplying all the internal values (font-size, drop-shadow distance, etc) this is because browsers handle scale (`zoom` or `transform:scale()`) for the internal SVG differently so multiplying the values in style gives the most consistent results cross-browser.

My suggestion is that you use percentage font-sizes for inline sizes. For example:

https://jsfiddle.net/bigtimebuddy/zgf3q6vu/

```html
<span style="font-size:80%"></span>
```

Alternatively, if you want to use absolute sizes, make sure to multiply them by the Renderer's `resolution`.
