### ISSUE TITLE
Bug: Different cursor/event (hit test?) behaviour for Graphics between v6 and v7, and depending on stage.interactive = true/false

### ISSUE THREAD

**Issue by TobiasWehrum** [pixijs/pixijs#9235]
### Current Behavior

When a Graphics instance A overlaps another Graphics instance B, the behaviour is different depending on PixiJS version and whether stage is interactive:

- v6, `stage.interactive = true/false`: The part of B that is obscured by A is clickable and shows B.cursor.
- v7, `stage.interactive = false;`: Same behaviour as v6.
- v7, `stage.interactive = true;`: The part of B that is obscured by A is not clickable and doesn't show B.cursor.

### Expected Behavior

The behaviour should be the same independently of whether `stage.interactive` is `true` or `false`. Additionally it should not differ from v6 (unless this change was intended).

### Steps to Reproduce

1. Open the following fiddles.
2. Point your cursor to the part where the red circle B is obscured by the white circle A.
3. Observe whether the cursor is a pointer. (Fiddle 1 and 2 "yes", fiddle 3 "no")
4. Click and observe whether an alert opens. (Fiddle 1 and 2 "yes", fiddle 3 "no")

Fiddle 1: v6, `stage.interactive = true;`: https://jsfiddle.net/TobiasW/avzgphd3/4/
Fiddle 2: v7, `stage.interactive = false;`: https://jsfiddle.net/TobiasW/bLdjp27z/2/
Fiddle 3: v7, `stage.interactive = true;`: https://jsfiddle.net/TobiasW/j3eqoznf/3/

### Environment

- **`pixi.js` version**: 7.1.4
- **Browser & Version**: 110.0.1 (64-Bit)
- **OS & Version**: Windows 10
- **Running Example**: See "Steps to Reproduce"

**Comment by rmercesGazeus** [comment]
I got this problem too.
If a graphic object is inside some object with interactive true then the graphic object will not trigger any event

**Comment by rmercesGazeus** [comment]
i got this too.

**Comment by Zyie** [comment]
Hey!

So this was an intentional change in v7 where non interactive elements would block interactions. This was to better emulate the native behaviour of the browser

However we recognised that this is not how a lot of our users expect the library to work and this makes upgrading from v6 to v7 a bit of a pain.

In the upcoming `v7.2.0` release we have made a lot of changes to make it possible to get similar behaviour to v6.

So for this situation you could set the default `eventMode` to `passive`
```ts
const app = new PIXI.Application({
    width: 120, 
    height: 100,
    eventMode: 'passive'
});
```
This can also be changed per object e.g `sprite.eventMode = 'static'`
This change also deprecates `sprite.interactive` in favour of `sprite.eventMode`

Feel free to open up this again if this does not give you the behaviour you need
