### ISSUE TITLE
Bug: Using PixiJS with Typescript throws events error

### ISSUE THREAD

**Issue by pimhakkert** [pixijs/pixijs#9380]
### Current Behavior

When using PixiJS in Typescript files an error is thrown when I hover my mouse over any area in the canvas. I'm using the viewport plugin, but the error is thrown in the EventBoundary.js file within Pixi itself.

`Uncaught TypeError: currentTarget.isInteractive is not a function`

It's on this line in the `hitTestMoveRecursive` function:
`const isInteractiveTarget = currentTarget.isInteractive();`

### Expected Behavior

No errors should be thrown when normally using PixiJS in Typescript files.

### Steps to Reproduce

Write a basic PixiJS + viewport implementation in Typescript.

### Environment

- **`pixi.js` version**: *7.2.4*
- **Browser & Version**: *Firefox 111.0.1*
- **OS & Version**: *Windows 10*
- **Running Example**: *N/A*

### Possible Solution

No idea on a solution, but my fix was to import Pixi and Pixi-viewport in a Javascript file, instantiate my objects there, and import those objects in my Typescript files. It's a hassle, but it works as a temporary solution.

**Comment by iRalph** [comment]
I also encountered the same issue, and after downgrading pixi.js to v7.1.4, everything is working fine now.

**Comment by akryvasheyeu** [comment]
I spent some time investigating. 
I am using `@pixi/react` in my project and I see this: webpack resolves DisplayObject from `@pixi/display` twice, but DisplayObject.mixin() is called once for the first import.

I found a workaround https://github.com/webpack/webpack/issues/13252#issuecomment-828587290

**Comment by Zyie** [comment]
With how pixi is packaged it is possible to run into issues like this

We have a wiki that explain how to update pixi and not run into issues like this: [Upgrading Pixi](https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS)

Feel free to reopen if this doesn't solve your issue

**Comment by hrueger** [comment]
for anyone having he same issue, maybe the following helps:

I was using a pixi plugin which depended on pixi@6. That also causes this error. When using yarn resolutions (for example) to pin this to 7, it starts working.

**Comment by levymateus** [comment]
I'm my game, i get this error when a mouse events and particle-emitter run at the same time in the scene. I solve disabling the `eventMode` to `eventMode=none`.

**Comment by baophungchi** [comment]
> I also encountered the same issue, and after downgrading pixi.js to v7.1.4, everything is working fine now.

I downgrading pixi.js to v7.1.4 but no resolve this issue.

**Comment by michael-ts** [comment]
@Zyie I'm not using any of this packaging nonsense (it doesn't make sense to waste time trying to figure this out for a PoC). I'm just trying to get some of the sample code working using the CDN or release versions.  pixi-cull apparently doesn't work with version 8, so I'm using 7.4.2.  My code looks like this:

import * as PIXI from 'https://cdn.jsdelivr.net/npm/pixi.js@7.4.2/+esm'
import { Viewport } from "https://cdn.jsdelivr.net/npm/pixi-viewport@5.1.0/+esm"
import { SpatialHash } from "./pixi-cull.es.js"

I downloaded pixi-cull.es.js from the releases page, version 2.2.

Unfortunately, as I'm not upgrading *anything* and not even using npm the link you provided sheds no light on potential fixes.

I'm not able to use version 7.1.4 because then I get this error:
The requested module '/npm/@pixi/utils@7.1.4/+esm' does not provide an export named 'deprecation' (at +esm:7:66)

**Comment by michael-ts** [comment]
If anybody could point me to the correct CDN versions (of pixi, pixi-viewport, and pixi-cull, ES module format) I would be very grateful.  I have tried quite a few already, but they all wind up with some kind of event errors when I move the mouse over the Pixi canvas.  I even copied a working codepen and used the exact version number it was working with and got the same result.
