### ISSUE TITLE
Bug: Extract plugin doesn't work with HTMLText

### ISSUE THREAD

**Issue by RhapsodY-69** [pixijs/pixijs#9567]
### Current Behavior

When using extract plugin to extract app.stage to png HTMLText is absent

### Expected Behavior

HTMLText is not absent in extracted png

### Steps to Reproduce

https://jsfiddle.net/w827Lqop/

### Environment

- **`pixi.js` version**: *7.2.4*
- **Running Example**: *<https://jsfiddle.net/w827Lqop/>*

### Additional Information

Image dimensions are 1px*1px, when I try to extract just htmlText

**Comment by bigtimebuddy** [comment]
HTMLText renders async, so you need to wait for it to render before you can use it with extract:
https://jsfiddle.net/bigtimebuddy/v1kfb53x/

**Comment by RhapsodY-69** [comment]
Thank you! But why should I call updateText() manually? @bigtimebuddy

**Comment by bigtimebuddy** [comment]
Good question. Consider this code:
```js
const texture = Texture.from('path/to/file.png'); // lazy load image
const sprite = new Sprite(texture);
renderer.
```
In this case, when you try to extract the `sprite`, it's not going to be visible until the texture has finished loading behind the scenes. So you need to wait for it instead.
```js
const texture = await Texture.fromURL('path/to/file.png'); // async load
const sprite = new Sprite(texture);
```
HTMLText is a little like this. It's not visible right away so the rendering is asynchronous. This is different from Graphics, Text, BitmapText which all (generally) render synchronously.

So you need to call `updateText()` in order to handle when the HTMLText is visible and ready to show like you would any external resources. A `setTimeout` is not a great way to handle this, but here's an example of why you're example doesn't work: https://jsfiddle.net/bigtimebuddy/w3u5vgb2/. The `text` element needs to added to the scene before the timeout so that it internally can call `updateText()`.

Hope that helps clarify.
